### ISSUE TITLE
"Subsystem Targeting Bracket" disappear in recent nightly

### ISSUE THREAD

**Issue by Amin442** [scp-fs2open/fs2open.github.com#1830] opened 2018-08-16 00:07 UTC
as title, recent nightly (I tried 2018-05-06 and 2018-08-14) do not have the "Subsystem Targeting Bracket".

![fs2_open_3_8_0_x64_avx 2018-08-16 07-47-20-50](https://user-images.githubusercontent.com/42396791/44179625-777a4400-a12a-11e8-9726-16d068578ebd.png)

**Comment by asarium** [comment] 2018-08-17 11:32
I had some trouble reproducing this reliably in the past. When does this happen for you? A single mission which shows this issue would be very helpful for fixing this.

**Comment by Amin442** [comment] 2018-08-17 12:43
It happen when using recent nightly.
Here is the mission for scan Sathanas.

https://www.youtube.com/watch?v=C91TX1BuKCA
(mission begin in 03:20) 

I noticed the problem because its too hard to scan large target without the Subsystem Targeting Bracket.(the small bracket on target turret/subsystem)

**Comment by tomimaki** [comment] 2018-08-22 19:38
Duplicate of #1655

**Closed** 2018-09-04 13:07 UTC
Labels: duplicate
