### ISSUE TITLE
UTF-8: Crash if Training Messages contain Prompts with Special Character Keys

### ISSUE THREAD

**Issue by NovachenFS2** [scp-fs2open/fs2open.github.com#3163] opened 2021-01-23 18:46 UTC
If Unicode Mode is active, the game crashes if a training message with a key prompt appear where the prompted function was set on a key that has a special character in it.

Examples for such keys are ä, ö, ç or ñ which are present on some keyboards.

I am playing with "$Disable built-in translations: Yes"

Interestingly, the game still calls Backspace "Rücktaste" in the german language setting nevertheless. So it is still translated.
But as the special character keys are not displayed in the Config Screen and in the Hotkey Tips in the directives monitor at all right now, this is maybe only some kind of UTF-8 oversight regarding the Training Message Gauge :)

[fs2_open.log](https://github.com/scp-fs2open/fs2open.github.com/files/5860816/fs2_open.log)

**Comment by z64555** [comment] 2021-01-25 18:36
I believe @SelfGamer addressed this issue within Controls6, I remember him finding the issue while poking around for international keyboard support.

**Comment by SelfGamer** [comment] 2021-01-25 18:41
> I believe @SelfGamer addressed this issue within Controls6, I remember him finding the issue while poking around for international keyboard support.

With the new controls6, the underlying function completely changed, so this may indeed be fixed by it.
However, while I did encounter some issues, notably with localized tables and unicode mode, I did not encounter CTD's.
I suspect that the crash could come from either Unicode chars in the training message, or from backend trouble. If it is the latter, controls6 most certainly fixed this. If it is the former, then we need to investigate the training messages by themselves. Expected behaviour at the moment would be that the key just doesn't show if the character is non-ASCII and the game doesn't run in unicode mode (though, as with all text, an upgrade to an engine-internal unicode fallback font is desirable for the future).

**Comment by SelfGamer** [comment] 2021-01-25 18:59
@NovachenFS2 Can you detail how exactly you can reproduce this?
I've started the game with "$Disable built-in translations: Yes" and "Unicode mode: No", set the Audio language in Knossos to german, and the training message worked fine-ish (a broken ü as expected, but the rest or Rücktaste showed).

Looking at the log suggests that you play with "Unicode Mode: Yes". If that is indeed the case, did you run into a parsing issue with the tstrings.tbl? Cause that is what is preventing me from testing this issue in Unicode mode (known issue, #2994).

**Comment by NovachenFS2** [comment] 2021-01-25 21:36
Yes, this problem only appear in Unicode Mode.
I am using my multi-language interface, so i have tables, that are encoded with UTF-8, and they are working fine... except in this situation.

The problem are not the special characters by itself, they are displayed in a normal training message.
The crash only happens if a key command prompt includes a Special Character.

The following training message cause the crash in my case:
> Jetzt bringen sie Ihren Jäger zum völligen Stillstand. [Drücke $backspace$]
(translation: Now bring your fighter to a complete stop. [Press $backspace$])

The $backspace$ is the problematic key command prompt in this case, because the game translated it into "Rücktaste" which contain a special character. (no idea if this name is hardcoded into the game code or is received from the operating system's active keyboard layout)
This crash is reproduceable with every other special character key. It would also happen if i rebind the backspace function (or any other that is prompted during the trainings) to Ä or Ö.
However, a crash only happens if a key command prompt is used in a training message.
The game does not crash if such prompt is used in the Directives Gauge however.

In this example this Hotkey tip is displayed:
> Drücke R

The ücktaste is missing in this case.
Together with the error message i got in the crash, it seems, that key names are not being converted into UTF-8.

AFAIK it was said, that it would be a bigger task to change the control code of the game, so that all keys are also displayed properly.
But well, right know it would be a start, that the game does not crash anymore :).
So the game should have atleast the same behaviour as in the directives gauge.

**Comment by SelfGamer** [comment] 2021-01-26 04:09
Ah, that explains it. Thanks.
A bit of digging and I think that it's caused by an implementation curiosity.
Before the controls code rework, all input names were hardcoded into the code. The code is stored in the Latin-1 codepage (not a good thing, actually), thus the encoded Rücktaste was not valid utf-8 and would trigger a panic once it's processed.
z64555/fs2open.github.com#4 should fix this once the new control code comes through, as it pulls the key localization from SDL, which _should_ be utf8. At least I am able to bind Ä to targeting without issue. Also, backspace is then also called Backspace, german OS-side, so that particularity also drops.

**Comment by SelfGamer** [comment] 2021-01-26 05:06
Alright, this is a hotfix which should temporarily fix the issue until the proper fix in the controls code comes along.

**Closed** 2021-01-27 18:52 UTC
Labels: bug, localization
