### ISSUE TITLE
Turning with the mouse is very laborious

### ISSUE THREAD

**Issue by warrickb** [scp-fs2open/fs2open.github.com#2451] opened 2020-06-07 14:52 UTC
Right now if you use the mouse to turn it takes an excessive amount of panning even on the highest sensitivity.  Really bad for repetitive strain injury - and personally I have had to stop playing a few missions in because of this - which is a shame as I missed out on this great game the first time around.

Lots of games get around this problem very well, and actually have a much better mouse control scheme, by continuously turning when the mouse is offset from the centre of the screen.  Along the lines of:

pitchTurn = (mouseY - screenCentreY) * scaleY
yawTurn = (mouseX - screenCentreX) * scaleX

I am not saying to give an option to make the ship turn faster, but rather for it to continuously receive the signal to turn when the mouse is offset from the centre of the screen.

I tried to download and build the code on my Windows machine to patch this, but after hours of numerous issues I still can't get it to build unfortunately.  I can however get the original developer release to build and can see where to fix it there, but then of course it's missing all the enhancements and fixes :-/

**Comment by wookieejedi** [comment] 2020-06-07 14:55
There are actually scripts which do this, I can pass one along if you'd like.

**Comment by warrickb** [comment] 2020-06-07 15:01
Definitely would love any sort of fix for this as I was really loving the game!

_Personally_ IMHO I think the aiming would be a million times better like I suggest, and it should be the default.  For example this is a video of me playing Strike Vector Ex that has the turning scheme I mention.  It's a much faster game and I have no problems being pretty precise in it :P

https://www.youtube.com/watch?v=wK_qkWs6iP8

**Comment by Goober5000** [comment] 2020-06-07 17:18
> I should also note that many folks who play with a mouse really like the fine tuning/aiming, and that would be gone if the mouse used continual input.

Agreed.  The precise mouse aiming is very good for sniping.

> Personally IMHO I think the aiming would be a million times better like I suggest, and it should be the default.

We're not changing the default.

**Comment by The-E** [comment] 2020-06-07 18:39
> _Personally_ IMHO I think the aiming would be a million times better like I suggest, and it should be the default. For example this is a video of me playing Strike Vector Ex that has the turning scheme I mention. It's a much faster game and I have no problems being pretty precise in it :P

As Goober mentioned, we are not changing the default. There may be some merit in building a control scheme like that as an option, but one of the primary objectives of FS2Open as a project is to preserve the original gameplay of FreeSpace 2 as designed by Volition as purely as possible. Since the mouse control method they chose is part of that, we will not be removing it or changing the default.

**Comment by warrickb** [comment] 2020-06-08 03:07
Yeh I understand that my preference may not be everyone's - and also the point about preserving the original game (It's amazing work how well the game has been updated and remains faithful).  It's why I specifically mention about it not effecting the achievable physical rate of turn, but rather it being a continuous turn input that feeds into that.  It's basically acting like a Joystick input in that case.

My 40+ year old gaming wrists would really love a simple checkbox for that! :-)

**Comment by X3N0-Life-Form** [comment] 2020-06-08 08:33
One thing I though would be neat is if you could switch the mouse control scheme on the fly with a simple key press or something.
eg. switch to "joystic-style" when you need to make hard, continuous turns, then back to "fps-style" when you need to actually aim.

**Comment by wookieejedi** [comment] 2020-06-08 13:19
FYI I actually tried to implement this in the code and as it turns out it's a lot more work then I originally thought. Main reason is that the mouse itself physically doesn't automatically re-center like a joystick. Thus if the mouse acts like a joystick it will move the ship in whatever direction the mouse is facing, and this it becomes rather annoying if you use free look, or pause the game and move the mouse then come back to the game and your mouse is now somewhere else and your craft is now moving in that direction. 

For all the folks here, there actually is a script which lets you use the mouse as a joystick, and can be toggled on and off with the click of a button. 
[https://www.hard-light.net/forums/index.php?topic=44634.0](url)

**Comment by warrickb** [comment] 2020-06-09 12:02
> For all the folks here, there actually is a script which lets you use the mouse as a joystick, and can be toggled on and off with the click of a button. This script still has that inherit problem though of not re-centering the mouse after pauses or freelook though (which again is a much harder then one would think fix.
> [https://www.hard-light.net/forums/index.php?topic=74435.0](url)

Thank you so much!  That is so much better already after a bit of tweaking - particularly removing the part where it tries to adjust where the cursor is drawn based on sensitivity.

I am flying now :-)

**Comment by warrickb** [comment] 2020-06-10 08:30
I will try and spend sometime tweaking that script further next week.  I had to make the cursor it was drawing with lines more apparent.

I would dearly love to have strafing combined in the same script if possible but haven't managed to find relevant info on if that is possible - and I understand it may not be what purists want.

Not sure where the best place is to share the script when I have finished with it if anyone is interested - I guess on the hard-light forums?

**Comment by wookieejedi** [comment] 2020-06-30 17:03
For anyone wanting the script which adds this functionality simply DL and drop in your tables folder: [https://github.com/wookieejedi/FSO-Scripts/tree/master/Joystick-Mouse](url)

**Comment by warrickb** [comment] 2020-07-15 03:19
@wookieejedi Great, and thank you!  I will definitely have a look at that.  It would be cool to have a selection of these kind of optional but perhaps popular scripts installed by default and easily enabled/disabled from the UI.

**Comment by Goober5000** [comment] 2020-08-05 19:04
Closing, as this seems to be resolved.

**Closed by Goober5000** 2020-08-05 19:04 UTC
Labels: not a bug
