### ISSUE TITLE
Audio voice duration

### ISSUE THREAD

**Issue by luca2125** [scp-fs2open/fs2open.github.com#3202] opened 2021-02-08 19:35 UTC
Hi,

I have replaced the original audio voice with other wav voices that are a bit longer.

Unfortunately in the training missions and other sometimes the voice stop before complete the message and start the next voice probably becouse the original voice is shorter.

I ask if is possible add a control to wav voices files that check if the audio is playing and wait until finish before play the next voice.

Thanks !

**Comment by Goober5000** [comment] 2021-02-08 20:33
FreeSpace is already supposed to wait until the voice is complete before moving to the next message.  However, it is possible that the missions themselves contain incorrect voice delays.  If that is the case, the problem is with the mission file, not the code.

Can you upload a video to illustrate the problem?

**Comment by luca2125** [comment] 2021-02-09 19:08
Thank you for your response:

This is the first training mission of FSO:
https://drive.google.com/drive/folders/12GTSiDwt74i8IfCFKQC0_ncpMueDjd8o?usp=sharing

As you can see the voice stop before complete all text.

Please let me known if is possible fix it.

Thanks !

**Comment by Goober5000** [comment] 2021-02-11 04:08
Oh, I see what the problem is.  Training messages work differently from regular messages.  It is possible for a training message to be cut off prematurely.

You can see the event in the mission file Training-1.fs2:
```
   ( training-msg 
      "Welcome Message" 
      "Welcome Message" 
      0 
      10 
   )
```
This can be found in the Welcome Message event.  The message will be stopped after 10 seconds, regardless of how long the sound file is.  To change this behavior, it is necessary to edit the mission file and increase the 10 second delay.  I also recommend to increase the 12 second chain delay of the Target event which is the next event in the list.

It is necessary to make these adjustments for every event which has a wrong delay.  Unfortunately the mission is designed with a delay which works for English, but the mission designer did not think about other languages.

**Comment by luca2125** [comment] 2021-02-11 08:34
Thank you for your response.

I have changed the voice to all fso missions and many other 10 additional missions  (ex. Babylon, blueplanetcomplete, WingCommanderSaga, etc ..).

I think there are not less 200/300 missions.

This problem teorically can be present on  every mission or only training mission ?

Thanks !

Marco

**Comment by Goober5000** [comment] 2021-02-11 14:23
The problem *should* only happen on training missions.  Normal messages in normal missions have the behavior I mentioned, which is to wait until the voice file is complete before playing the next message.

**Comment by luca2125** [comment] 2021-02-11 14:40
Many thanks !

if for example I will try in the future to fix it in the source code, can you please let me known what file I need to change ?

In short i like to extend the control of voice complete to training mission also.

I don't think this problem will be fixed officially in the future release.

Thanks !

**Comment by Goober5000** [comment] 2021-02-11 16:04
Well, maybe what we can do is add an optional flag, perhaps in game_settings.tbl.  Look in missiontraining.cpp, in the function `message_training_queue_check`.  Add the following code after the `Training_failure` check and before the loop.

```
	// don't pre-empt any voice files that are playing
	if (fsspeech_playing())
		return;
	for (int i = 0; i < Num_messages_playing; ++i)
	{
		if ((Playing_messages[i].wave.isValid()) && (snd_time_remaining(Playing_messages[i].wave) > 250))
			return;
	}
```

If this works, I can open an official pull request to add a flag.

**Comment by luca2125** [comment] 2021-02-11 16:36
Many thanks !

I will save this message on a text file becouse is important.

I can’t try now becouse I have visual studio and I have not cmake installed (I never compile a source without windows project file).

To be honest I waiting for fate of galaxy to play again, so if in the meantime is possible do this change it is a very good news !!

Thanks !

**Comment by Goober5000** [comment] 2021-02-11 22:08
You're welcome. :+1:

**Comment by luca2125** [comment] 2021-06-29 16:17
I have tried to compile another opensource project with cmake but I get some problem and I don't why.

I admit that I don't have not too match familiarity with linux in general.

Becouse I'am interested about ths modification, If you are still working on this project I ask if you can 
temporarily test your code (just replace a longer dialogue in some mission) and see if work.

If yes can be very useful apply this modification.

Thanks !

**Comment by Goober5000** [comment] 2021-07-10 04:15
Sorry for the delay in responding.  I will see about opening a pull request for this feature.  I still have the code I wrote on Feb 11.

**Comment by luca2125** [comment] 2021-07-10 06:29
Thank you !! please let me known.

**Comment by Goober5000** [comment] 2021-07-17 02:16
It was a little trickier than I thought, but I figured it out.  See #3559.

Note that with this flag enabled, messages will play completely even if you might normally expect the message to be cancelled.  For example, if the Instructor tells you to target his fighter, normally he will stop the current message as soon as you press the targeting key.  With this flag enabled, he will finish the message.

**Closed** 2021-07-17 04:10 UTC
Labels: sound

**Comment by luca2125** [comment] 2021-07-17 05:34
Many thanks !

When will be official full release (not beta) of game ?

**Comment by Goober5000** [comment] 2021-07-17 15:17
You're welcome!

Our project generates new builds every night, but these are considered beta builds.  We are scheduled to have an official release soon, but it is delayed while we perform additional reviews on the controls code.  So we do not have an official scheduled date.  We hope it will be within one month.

**Comment by luca2125** [comment] 2021-07-17 15:48
This is very news, do you think in the future will be a graphics improve like for example with adding ray tracing or re-modelling / re-texture ? I find this game very good but sometime when I see other mod like this:

Tie Fighter Total Conversion
https://www.youtube.com/watch?v=jv_etDBLm_8

in my mind I ask: When will be ready Fate Of Galaxy ?

**Comment by BMagnu** [comment] 2021-07-17 15:56
None of the effects seen in that video need raytracing specifically.
If you're talking shadows on the cockpit, we support that by now, it just needs to be enabled.
If you're talking lights lighting up other ships, that's been a thing for a while now, and it's just a question of the light settings when you launch FSO and the parameters of the weapons fired.
If you're talking about shots lighting up the cockpit, that's implemented by #3445 and will (hopefully) eventually making it's way into the engine.
Or have I missed something you specifically mean?

**Comment by luca2125** [comment] 2021-07-17 16:15
No, It is clear now, I need only download the next version version when will be added.

Last question:

In the past I have worked with "Novachen" on a localization mod translation:

https://www.hard-light.net/forums/index.php?topic=96944.0

I short I have sent to "Novachen" the Italian Localization (Voice and text).

For my opinion can be usful if the mod of Novachen will be included in the installer (the user can choose the language of game while install the game) or eventually I can send my work to you if is possible.

Do you think this can be take in consideration in the future ?

**Comment by Goober5000** [comment] 2021-07-17 18:13
@NovachenFS2 might be able to comment on that

**Comment by NovachenFS2** [comment] 2021-07-18 13:29
I am not sure about what i can tell. Maybe i made this not clear in the NTP thread.

Currently i can not really work on NTP :(.
I received marco's files a while ago already to implement an italian translation (even i would only cover text).

But since an accident march last year my husband is in need of care sometimes and his condition went worse again a few months ago and is still not very well.
So between my work and the care for him i am lucky if i find time to relax with some gaming.

I still try to get together some moments to work on a 0.5.1 that would include the italian and an updated japanese translation... but well.. progress is only very slowly right now.

Sorry 😭

**Comment by luca2125** [comment] 2021-07-18 15:27
> I am not sure about what i can tell. Maybe i made this not clear in the NTP thread.
> 
> Currently i can not really work on NTP :(.
> I received marco's files a while ago already to implement an italian translation (even i would only cover text).
> 
> But since an accident march last year my husband is in need of care sometimes and his condition went worse again a few months ago and is still not very well.
> So between my work and the care for him i am lucky if i find time to relax with some gaming (or to talk to some friends at least).
> 
> I still try to get together some moments to work on a 0.5.1 that would include the italian and an updated japanese translation... but well.. progress is only very slowly right now.
> 
> Sorry 😭

I'am sorry for this ... please don't consider my post. I think you have more important things to do.

**Comment by Goober5000** [comment] 2021-07-18 18:50
> But since an accident march last year my husband is in need of care sometimes and his condition went worse again a few months ago and is still not very well.

I didn't know about this.  I'm sorry to hear it.  I hope his condition improves in the future.

**Comment by NovachenFS2** [comment] 2021-07-19 09:33
> I'am sorry for this ... please don't consider my post. I think you have more important things to do.

> I didn't know about this. I'm sorry to hear it. I hope his condition improves in the future.

First, thanks to both of you.
Second, it does not wonder me, that you did not know that so exactly, as i never said it so clear.
I still hoped, that i was able to handle all of this and also have time for some Freespace, as i call myself reliable and that game mean much to me. I am pretty heartbroken that I am leaving people hanging here. Not only in the translation effort, on some mods that are in dire need of an update aswell. 🤔
