### ISSUE TITLE
Unix standalones lose networking after 5 hours, for 5 hours

### ISSUE THREAD

**Issue by chief1983** [scp-fs2open/fs2open.github.com#1237] opened 2017-02-17 14:05 UTC
A little after 5 hours of being up, the multi.log goes blank, the server disappears from FS2NetD, and direct IP connection attempts fail.

Stranger still, apparently about 5 after that, somehow they wake back up and reconnect to FS2NetD, seemingly restarting the cycle.  I will monitor the behavior today and see if this one drops again  in about four and a half hours.  I added +Network to a debug_filter.cfg but there isn't anything useful in there, just some Frame 0 too long statements.

I am wondering if some kind of timer we modified is rolling over, and while it is a signed negative value, the server is broken, and when it rolls back to 0, it wakes up again.  That's the only hunch I have so far but it's probably wrong.  I just don't remember seeing this behavior before.  There is no terminal output either.  I can Ctrl+C to kill the client still, usually.  Even with sanitizers enabled, and under gdb, this behavior persists without revealing any clues (other than UBSAN errors I have filed reports for already, but probably not related).
```
02/17 02:04:45~   FS2NetD sent IDENT check
02/17 02:04:47~   FS2NetD sent game server update
02/17 02:06:47~   FS2NetD sent game server update
02/17 02:07:45~   FS2NetD sent IDENT check
02/17 02:08:47~   FS2NetD sent game server update
02/17 02:10:40~   Server has been active for 4 hours, 54 minutes, and 7 seconds
02/17 02:10:45~   FS2NetD sent IDENT check
02/17 02:10:47~   FS2NetD sent game server update
02/17 02:12:47~   FS2NetD sent game server update
02/17 02:13:45~   FS2NetD sent IDENT check
02/17 02:14:47~   FS2NetD sent game server update
02/17 02:16:45~   FS2NetD sent IDENT check
02/17 02:16:47~   FS2NetD sent game server update
02/17 02:18:47~   FS2NetD sent game server update
02/17 02:19:45~   FS2NetD sent IDENT check
02/17 02:20:47~   FS2NetD sent game server update
02/17 02:22:45~   FS2NetD sent IDENT check
02/17 02:22:47~   FS2NetD sent game server update
02/17 07:31:25~   Server has been active for 10 hours, 14 minutes, and 51 seconds
02/17 07:36:25~   Failed to send PING packet!
02/17 07:36:25~   FS2NetD sent PING
02/17 07:36:56~   FS2NetD WARNING: Lost connection to server!
02/17 07:36:56~   FS2NetD WARNING: Failed to send server disconnect packet!
02/17 07:36:56~   FS2NetD sent game server disconnect
02/17 07:36:57~   FS2NetD MSG: Login 'scpuser' is valid, session ID is 57873!
02/17 07:36:57~   FS2NetD MSG: Requesting login pilot stats for 'server' ...
02/17 07:36:57~   FS2NetD MSG: Got Pilot data
02/17 07:36:57~   FS2NetD sent game server start
02/17 07:36:57~   FS2NetD NOTICE: Connection to server has been reestablished!
02/17 07:36:57~   FS2NetD sent PING
02/17 07:36:57~   FS2NetD PONG: 166 ms
02/17 07:36:59~   FS2NetD sent game server update
02/17 07:38:59~   FS2NetD sent game server update
02/17 07:40:59~   FS2NetD sent game server update
02/17 07:42:59~   FS2NetD sent game server update
02/17 07:44:59~   FS2NetD sent game server update
02/17 07:46:59~   FS2NetD sent game server update
02/17 07:48:59~   FS2NetD sent game server update
02/17 07:50:59~   FS2NetD sent game server update
02/17 07:52:59~   FS2NetD sent game server update
02/17 07:54:59~   FS2NetD sent game server update
02/17 07:56:59~   FS2NetD sent game server update
02/17 07:58:59~   FS2NetD sent game server update
```

**Comment by chief1983** [comment] 2017-02-17 14:11
Additionally, some (but not all) of the servers are running with an experimental fix to prevent crashes on SIGPIPE, which didn't affect Windows standalones but crashes them on Linux and BSD like distros.  So I don't think it's related but thought I would add that here.
```
diff --git a/code/fs2netd/tcp_socket.cpp b/code/fs2netd/tcp_socket.cpp
index 4493de5..a37125d 100644
--- a/code/fs2netd/tcp_socket.cpp
+++ b/code/fs2netd/tcp_socket.cpp
@@ -109,6 +109,16 @@ int FS2NetD_ConnectToServer(const char *host, const char *port)
                ulong arg = 1;
                ioctlsocket(mySocket, FIONBIO, &arg);
 
+               // OS X - prevent SIGPIPE, which is generated when sending after receiver disconnected
+               // on other *nix use MSG_NOSIGNAL flag when sending data, see FS2NetD_SendData()
+#if defined(SCP_UNIX) && defined(__APPLE__)
+               int nosigpipe = 1;
+               if (setsockopt(mySocket, SOL_SOCKET, SO_NOSIGPIPE, (void*)&nosigpipe, sizeof(nosigpipe)) == -1) {
+                       my_error = errno;
+                       ml_printf("FS2NetD ERROR: Couldn't set SO_NOSIGPIPE on socket (\"%s\")!", strerror(my_error));
+               }
+#endif // SCP_UNIX && __APPLE__
+
                // blasted MS, probably need to use getaddrinfo() here for Win32, but I
                // want to keep this as clean and simple as possible and that means
                // using an actual standard :)
@@ -237,6 +247,13 @@ int FS2NetD_SendData(char *buffer, int blen)
 {
        int flags = 0;
 
+       // on Unix, prevent SIGPIPE, which is generated if receiver has disconnected
+       // the MSG_NOSIGNAL flag doesn't work on OS X
+       // on OS X, use setsockopt() with SO_NOSIGPIPE instead, see above
+#if defined(SCP_UNIX) && !defined(__APPLE__)
+       flags |= MSG_NOSIGNAL;
+#endif // SCP_UNIX && !__APPLE__
+
        socklen_t to_len = sizeof(sockaddr);
 
        return sendto(mySocket, buffer, blen, flags, (sockaddr*)&FS2NetD_addr, to_len);
```

Another netcode fix which attempt to fix the ping was in #609 which has been merged.  Not sure if it could somehow be responsible for this or not.  I know the server keeps pinging FS2NetD.  Perhaps we introduced some kind of overflow there?

**Comment by jg18** [comment] 2017-02-18 02:01
Wait, the SIGPIPE prevention  changes were merged? When did that happen? I'm surprised it wasn't noted on Issue #470.

I wouldn't think those changes would be related. They should just make the Unix standalone behave like the standalone behaves on Windows with respect to not crashing if there's an attempt to write to a broken pipe when the standalone communicates with FS2NetD.. If however this issue only occurs when those changes are applied then certainly the SIGPIPE prevention changes would look like the cause.

**Comment by chief1983** [comment] 2017-02-18 02:04
No, they weren't merged.  What I meant was that some of my standalones had that fix manually applied.  Some did not.  All were misbehaving so I don't believe that patch was somehow the cause of it.  And we seem to have determined that it was an issue with the timer code after all, so a patch for this bug should be coming soon.  See https://gist.github.com/asarium/22573852cdca18c7560039fcc73299b1 for what it will probably look like.  I'll let @asarium make the PR since he wrote the fix.  Then hopefully I can have a standalone up long enough to test that the SIGPIPE prevention changes actually work as intended, although I don't think they are harming anything and would like it merged before 3.8 regardless.

**Comment by jg18** [comment] 2017-02-18 02:06
Yeah as I noticed in my edit I realized I had misread your post. My next comment was going to be about changes to the timer code and wondering if that was the culprit. Glad to hear it's been tracked down.

**Comment by asarium** [comment] 2017-02-18 09:15
@chief1983 Does my patch actually fix the issue? I'll submit it as a PR if that's the case.

**Comment by chief1983** [comment] 2017-02-18 15:46
The one with the patch applied has been responsive since I started it over 20 hours ago.  It's definitely an improvement, only time will tell if it's completely fixed but I would expect it to be after these results.  So please feel free to submit the PR, then I'll get it on the rest of my standalones and start the clock :)

**Closed** 2017-02-18 17:57 UTC
