### ISSUE TITLE
Shadows are now almost impossible to see

### ISSUE THREAD

**Issue by DahBlount** [scp-fs2open/fs2open.github.com#1135] opened 2017-01-05 05:28 UTC
First reported by Darius.
July Build: 
![](http://i.imgur.com/mSTl6iQ.jpg)
Dec 31 Build: 
![](http://i.imgur.com/QPCk1VA.jpg)

Shadows are now very faint, practically impossible to see except for a few cases where you're very close to the shaded object as well as flatter lighting. I'm currently looking into it with Zacam and Darius.

**Comment by DahBlount** [comment] 2017-01-05 06:03
Update: This has been narrowed down to the August 27th build as the first occurrence... which also happens to be the day OpenGL Core Support was added, among a large pile of other graphics code changes.

**Comment by SamuelCho** [comment] 2017-01-05 08:33
This might have something to do how ambient factors were applied _twice_ via OpenGL's fixed function material/light model parameters which essentially scaled ambient light exponentially. I got rid of the exponential behavior in the transition to Core, thinking it was a bug and would make things less confusing. But I guess I have no choice if people really want their old light settings prior to the Core transition to work 1-1.

**Comment by asarium** [comment] 2017-01-05 09:01
If there was a good reason to remove the previous lighting behavior then it doesn't make sense to add that behavior again just so a few people don't have to change their lighting presets. It would be nice to know how to change the values so that the previous lighting is restored but IMO this doesn't require any changes if there is not an actual but in the rendering engine.

**Comment by DahBlount** [comment] 2017-01-05 09:04
@m!m The issue with the cmdline lighting settings is that they barely affect the visibility of shadows compared to the rest of the model. Darius tested quite a few times to see if he had just forgotten something but was unable to change the relative darkness of shadows compared to the rest of the model.

**Comment by DahBlount** [comment] 2017-01-05 09:06
It changes the overall darkness of the model as it used to, but it doesn't affect how dark shadows are relative to the little portions of a model, no emissivity light also has little to no effect on it.

**Comment by SamuelCho** [comment] 2017-01-05 09:20
Does it look any different with deferred lighting off?

**Comment by SamuelCho** [comment] 2017-01-05 09:40
I honestly have no idea. I'm just spitballing at this point. I barely touched the shadow code when bringing everything to OpenGL Core. The only thing related was maybe the ambient light behavior I changed which is why I suggested it. Because stuff that's shadowed essentially take on the ambient light.

**Comment by chief1983** [comment] 2017-01-05 13:37
Would it be a ton of work to release a custom current build with that behavior restored for comparison?  Or perhaps to make the old lighting settings enabled via mod setting or command line for mods that aren't supported and won't have settings updated any time soon?  Or, perhaps better, if there is a universal set of lighting presets that get closer to the original lighting "look", call those out and people could try to use those?  I had been hoping for defaults that would not look so drastically different from before but have been told that is a side effect of pbr or whatever, but if these ambient changes were more likely responsible that is interesting.  I imagine the pbr stuff is responsible for ultra shiny ships but that is probably another issue to be worked out.

**Comment by DahBlount** [comment] 2017-01-05 18:16
@SamuelCho So, testing with deferred lighting gives me slightly more apparent shadows when the casting and receiving objects are close together, but pretty much the same results for all other objects.

@chief1983 Like I said, we tested with the lighting cmdline params to see if it was possible to achieve the old look without much fuss. We were unable to get something even remotely like the old output.

**Comment by SamuelCho** [comment] 2017-01-05 20:32
Is that July build before or after PBR was committed?

**Comment by DahBlount** [comment] 2017-01-05 20:36
I do believe it was after PBR was merged. It certainly had HDR Bloom which was merged at the same time as PBR iirc.

**Comment by SamuelCho** [comment] 2017-01-06 07:18
I have https://github.com/SamuelCho/fs2open.github.com/commit/ee675a19b5b73b1ebfb271885903a41e608e24e0 which restores the old OGL compatibility profile ambient light behavior. But I don't think it'll do anything because I can't reproduce your problem anyway.

I ran Icarus on a recent build (https://github.com/scp-fs2open/fs2open.github.com/commit/6839d1c3d186658c34071e21748db5fc695ffa0a) and compared it with this build: https://github.com/scp-fs2open/fs2open.github.com/commit/60bee02f9

I don't see shadows in both builds.

From 60bee02f9 which is before the OpenGL Core commits
![60bee02f9](https://cloud.githubusercontent.com/assets/426809/21710272/6db492d4-d39c-11e6-89ac-77424e63537f.png)

From 6839d1c3d:
![6839d1c3d186](https://cloud.githubusercontent.com/assets/426809/21710292/8e703e74-d39c-11e6-8e9a-bfc7cbb202fd.png)

So faintly seeing the shadows honestly may be the correct behavior?

**Comment by DahBlount** [comment] 2017-01-06 07:21
Huh, what are your lighting settings? Myself and many others can reproduce the very apparent shadows seen in the July build.

**Comment by DahBlount** [comment] 2017-01-06 07:30
Let me do some more testing with presets off and no custom params.

**Comment by SamuelCho** [comment] 2017-01-06 07:37
I think the ambient behavior restoration fixes it.

Build using Herra Tohtori's settings.

Before Core:
![pbr_before_core](https://cloud.githubusercontent.com/assets/426809/21710797/cd33461c-d39f-11e6-80b9-01ba93dae011.png)

After Core:
![pbr_after_core](https://cloud.githubusercontent.com/assets/426809/21710800/d196409c-d39f-11e6-94ad-8ff6ae539027.png)

After https://github.com/SamuelCho/fs2open.github.com/commit/ee675a19b5b73b1ebfb271885903a41e608e24e0

![pbr_after_fix](https://cloud.githubusercontent.com/assets/426809/21710808/de130a30-d39f-11e6-8106-66d487836bab.png)

**Comment by DahBlount** [comment] 2017-01-06 07:42
So it does. I still can't fathom why the original ambient factor usage was as an exponential. Perhaps a better way to make ambient factor more effective would be to increase its max possible value to something like 256 and get rid of the clamping that occurs (it gets clamped between 0.2 and 1.0)?

**Comment by MageKing17** [comment] 2017-01-06 07:49
> increase its max possible value to something like 256

Er... is that not the current maximum? I'm pretty sure an ambient factor of either 127 or 128 is the default and translates to a modifier of 0, with lower values decreasing the mission's defined ambient light and higher values increasing it. Either 255 or 256 should translate to a positive modifier of 1.0, which means it can bring a mission with a defined ambient light level of 0 up to the cap.

**Comment by DahBlount** [comment] 2017-01-06 07:58
An input of 128 would translate to a modifier of 1.0 based on what I've looked through, additionally, it clamps all ambient factors between 0.2 and 1.0, so you can't have a negative factor.
The default value of `Cmdline_ambient_factor` is 128. It gets divided by 128.0 and the result is `*=` with the first three elements of `GL_light_ambient`, which are then clamped between 0.02 and 1.0.

**Comment by MageKing17** [comment] 2017-01-06 08:14
Sorry, I didn't realize the behavior of the ambient factor had changed to a multiplier; if you look at Swifty's commit linked above, you can see the restoration of the old behavior I was describing.

**Closed** 2017-01-06 17:49 UTC
