### ISSUE TITLE
Assert: "count < max_floats"

### ISSUE THREAD

**Issue by naomimyselfandi** [scp-fs2open/fs2open.github.com#3265] opened 2021-03-01 17:50 UTC
From @MjnMixael:

> BtA 1.5.8 gets an this assert on FSO builds from Feb 1 2021 or newer. Suspect a change in #3079 causes the issue. Unclear what data FSO is tripping over here, but the mod worked before this change.

The assert is in parselo.cpp, line 3179.

**Comment by Goober5000** [comment] 2021-03-01 20:45
I'll take a look.

**Comment by naomimyselfandi** [comment] 2021-03-01 23:50
@Goober5000 Mjn eventually tracked it down to a typo in one of our .tbl files - `0..5` instead of `0.5`.

**Comment by Goober5000** [comment] 2021-03-01 23:59
Oh ok, thanks for the update.  I'll call this Not-A-Bug then.

**Comment by Goober5000** [comment] 2021-03-02 00:00
On second thought, I'll keep it open to see if I can report the error in a clearer way.

**Comment by naomimyselfandi** [comment] 2021-03-02 03:27
Well, philosophically, I don't think asserts should get tripped by a data issue. Practically, it meant we didn't get a filename or line number. (BTA is about as large as you'd expect, so if Mjn hadn't been familiar with #3079, I don't know how we'd have _ever_ found it.)

**Comment by Goober5000** [comment] 2021-03-02 14:27
Agreed, asserts should only be used to catch programming mistakes.  This should be caught with `error_display` like the rest of the parsing validation.

**Comment by Goober5000** [comment] 2021-03-02 18:07
#3269 will prevent this error, but I will make another PR to actually fix the error reporting here.

**Comment by naomimyselfandi** [comment] 2021-03-02 18:33
> #3269 will prevent this error (by catching and reporting a different error), but I will make another PR to actually fix the error reporting here.

Just a heads-up that this was from a .tbl file (I think it was species_defs.tbl), not a FRED annotation. It sounds like your fix will address both - I just wanted to make sure that was clear because the title of your new issue mentions annotations in particular.

**Comment by Goober5000** [comment] 2021-03-02 18:38
Yeah, I loaded up the error and and tested it directly from the mod - it was caused by hud_guages.tbl.  The two issues are both related to number parsing, which is why the new PR mentions both issues.

**Comment by Goober5000** [comment] 2021-03-11 00:19
Fixed by #3269 and #3271.

**Closed by Goober5000** 2021-03-11 00:19 UTC
