### ISSUE TITLE
Nested Subsystems Do Not Get Destroyed When Parent is Destroyed.

### ISSUE THREAD

**Issue by AndrewofDoom** [scp-fs2open/fs2open.github.com#605] opened 2016-05-06 00:09 UTC
Test mod here: [subsystem_test.zip](https://github.com/scp-fs2open/fs2open.github.com/files/251382/subsystem_test.zip) Run the test mission and destroy subsystem trand1 on the hastily made Argo test dummy. Trand2's subobject will be removed but the subsystem will not be destroyed.

**Comment by Goober5000** [comment] 2016-05-30 18:05
I wonder if this should be rolled into 3.7.4.

**Comment by asarium** [comment] 2016-05-31 08:24
As far as I can tell there is no central place for handling damage to subsystems so fixing this bug will require some additional investigating to determine how it should be handled. I don't think it should be added to the 3.7.4 milestone.

So far I have identified one problem that might be caused by fixing this bug:
- SEXPs can repair subsystems. If a parent subsystem gets destroyed and the child subsystem is also destroyed, what would happen to the child if the parent is repaired?

**Comment by AndrewofDoom** [comment] 2016-06-01 05:49
That's a good question. A question I had never thought of at all. The most logical answer (at least to me) is to also repair the up the chain as well.

**Comment by ln-zookeeper** [comment] 2016-06-01 12:29
Automatically repairing the child just because the parent was repaired doesn't really make sense to me, because there's nothing wrong with the state of the child being destroyed while the parent is alive; that's what you end up with if you simply shoot the child first, nothing's going to break because of it. The trickier case is surely when the child gets repaired, but the parent is still destroyed; if the child dies automatically when the parent dies but afterwards a SEXP repairs it, you end up in an unnatural and likely unintended state. However, that seems like it'd be very rare, and it's something the mission designer could almost always easily safeguard against.

Anyway, there is no universally right answer to whether a child subsystem should be automatically destroyed when the parent dies. Maybe it's a turret attached to a spinning central part of the ship, and when destroyed, the latter just stops spinning while the turret should remain operational. Or maybe it's a small point defense gun mounted on top of a big subsystem and should blow up when that one blows up. The only way to cater to both is to have a submodel or subsystem property specifying whether the subsystem should die when its parent (if any) dies.

**Comment by DahBlount** [comment] 2016-06-01 17:10
Perhaps we could include a SEXP for both the singular subsystem and the subsystem + children? If we didn't want to do that, perhaps a subsystem flag?

**Comment by asarium** [comment] 2016-06-01 17:23
A subsystem flag and a SEXP with an optional flag to change the behavior should work pretty well.

**Comment by DahBlount** [comment] 2016-06-02 02:45
I concur. I might take a further look into this.

**Comment by asarium** [comment] 2016-06-04 22:03
Should this still be part of the 3.7.4 release? IMO the discussion has shown that a proper fix for this requires additional engine features.

**Comment by DahBlount** [comment] 2016-06-04 22:54
I see no reason for this to be delayed until a certain release. You could argue this is an enhancement instead of a bug as the only changes are additions to the code instead of fixing present code, so with that in mind, I say we should remove the 3.7.4 milestone.

**Comment by Goober5000** [comment] 2016-06-05 04:35
I agree with removing the milestone target; the situation is complicated enough that additional discussion is useful.

But I don't think additional engine features are necessary.  I think the hierarchy problems can be solved very easily by just treating the subystems as a dependency chain.  Subsystems should only be destroyed or repaired if they are dependent on another subsystem that was destroyed or repaired.

To elaborate, when a parent subsystem is destroyed, all child subsystems should also be destroyed because the children depend on the parent in that sense.  However, when the parent is repaired, the children should not be repaired because the parent does not depend on them.  On the other hand, if one of the child subsystems are repaired, the parent subsystem should also be repaired but the sibling subsystems should not be repaired.  Using this strategy is logical and adheres to the principle of least astonishment.

Now as for Zookeeper's example where a turret base is destroyed but the turret itself remains operational, this is completely inconsistent with every precedent in FS model handling.  When a subobject's strength reaches 0, the blown-off code is called.  Either the submodel is removed or it is replaced with a -destroyed submodel.  Zookeeper's example is such a unique special case that a new model would have to be designed and new model code be written for it anyway, and since that's the case let's not burden the existing usage with an imaginary future problem.

Note in particular what AndrewOfDoom posted as a test mod.  The model code *already* handles the removal of child subobjects.  When Trand1's subobject is destroyed, Trand2's subobject is destroyed as well.  The only error here is that the subsystem strength does not reflect the state of the subobject.

**Comment by DahBlount** [comment] 2016-06-05 17:35
I see. This may even be a simpler fix than I'd original figured would be needed then.

**Closed** 2019-06-06 05:48 UTC
Labels: bug
