### ISSUE TITLE
Normal maps not rendered with fs2_open_3.7.4_RC2

### ISSUE THREAD

**Issue by maurossi** [scp-fs2open/fs2open.github.com#616] opened 2016-05-29 12:19 UTC
Hi, I'm reporting a problem seen on Ubuntu 16.04 in 3.7.4RC2 the normal maps are not rendered with all GPUs, while with 3.7.2 normal maps were OK. I have not checked with Windows versions.

Apitrace traces of Star Wars Original Trilogy's Tie Interceptor show that with 3.7.2 the details on the Ties wings quadanium steel armor are visible, while on 3.7.4_RC2  just planar surfaces are rendered.

qapitrace retracer can be used to see the differences on screen and in the shaders

You can find the traces here: 
https://drive.google.com/folderview?id=0B_OFHiIqgpSFSFFyOVBYVHdOODg&usp=sharing

Mauro

**Comment by asarium** [comment] 2016-05-29 12:35
I can reproduce the issue using the provided trace files. For me there are shader compilation errors ('m using the AMD Mesa drivers on Fedora 23) when entering the tech room.

What GPU and drivers are you using? There are a couple of issues with the open source drivers because FSO currently uses a feature combination that is not supported by them. There is an ongoing effort to bring FSO to OpenGL Core compatibility which will fix these issues but that won't happen until after the next release.

**Comment by maurossi** [comment] 2016-05-29 13:28
Hi asarium,

thanks for feedback and info, now I've seen issue #511 "Switch to OpenGL Core Profile",
so the problem is the new combination of features in 3.7.4, but could these new feature controlled by command line option flags, in order to avoid regression?

I'm using mesa git (oibaf ppa)

My systems specs:
AMD Phenom X3 with ATI RS780 GPU (on 790GX-G65 mothboard) mesa gallium radeon driver
AMD Athlon X2 with Nvidia G210 with mesa gallium nouveau driver
AMD Athlon X2 with GeForce 7300LE with mesa gallium nouveau driver

I am available to continue debugging normal maps and if you need further test efforts in upcoming releases.

Mauro

**Comment by MageKing17** [comment] 2016-05-29 13:39
> so the problem is the new combination of features in 3.7.4, but could these new feature controlled by command line option flags, in order to avoid regression?

Yes and no. Yes, the new features are controlled by command-line options, but I'd be surprised if adding `-no_deferred` to your command-line fixed the problem, because even outside of the new features, the renderer was heavily modified, so no, there's no way to just use the old code path.

However, if the problem is anything like other peoples' problems with disappearing textures, you might be able to get some results by using `-no_glsl` to disable shaders entirely; this will naturally mean fewer graphical bells and whistles, but I'm fairly certain the fixed function renderer still supports normal maps (although I could be wrong).

**Comment by chief1983** [comment] 2016-05-29 14:21
I think normal maps were the first shader exclusive rendering feature.

**Comment by maurossi** [comment] 2016-08-14 20:58
Hi,

I've found the root cause of the issue, it is related to mesa expecting '#version 120' set in GLSL code.

Double checked in the following ways:

1) building 3.7.4 with the change to set sflags  '#version 120\n' with linux build

2) running fs_open_3.7.4 with force_glsl_version=120 variable

`force_glsl_version=120 ./fs2_open_3.7.4 -mod Star_Wars_beta411,MediaVPs_2014 -fps`

So the issue is basically related to strict OpenGL GLSL compliancy of mesa.

For the time being, setting the variable allows to see the shaders.
Mauro

**Comment by niffiwan** [comment] 2016-08-14 21:44
Yes, unfortunately adding the version breaks other OpenGL implementations. See #235 for more details. #511 is longer term solution.

**Comment by asarium** [comment] 2016-08-26 19:48
This should be fixed by #844.

**Closed by asarium** 2016-08-26 19:48 UTC
