### ISSUE TITLE
Standalone assertion

### ISSUE THREAD

**Issue by chief1983** [scp-fs2open/fs2open.github.com#187] opened 2015-06-17 15:24 UTC
ASSERTION FAILED: "(objp != NULL) && (objp->type == OBJ_SHIP)" at network/multimsgs.cpp:6038

Not much else to go on at the moment, just the tail of the overall log:

Submodel 'thruster01c' is detail level 2 of 'thruster01a'
Loading model 'cmeasure01.pof'
Loading model 'debris01.pof'
Loading model 'debris02.pof'
Paging in mission messages
Ending level bitmap paging...
Level load took 1.557000 seconds.
Frame  0 too long!!: frametime = 1.502 (1.502)
Got event GS_EVENT_MULTI_STD_WAIT (35) in state GS_STATE_MULTI_MISSION_SYNC (38)
Got event GS_EVENT_MULTI_MISSION_SYNC (50) in state GS_STATE_MULTI_STD_WAIT (29)
ASSERTION: "(objp != NULL) && (objp->type == OBJ_SHIP)" at multimsgs.cpp:6038

**Comment by MageKing17** [comment] 2015-06-18 21:06
Unfortunately, the combined assertion doesn't tell us which precondition failed (or how far into the for loop this was).

**Comment by Echelon9** [comment] 2015-06-21 03:24
Yes, as a general point we shouldn't have combined assertions like that.
Separating them out into two lines would be preferable, however resolving that is distinct from the issue here.

**Comment by chief1983** [comment] 2015-06-21 14:05
I can look at improving that and seeing if it can crash there again.  Also I will try to determine what was running from the logs, and maybe find the players who crashed it if they are in the community.

**Comment by chief1983** [comment] 2015-11-25 20:14
Ok I never got around to hunting down who did it, not likely to find out anyway.  These might also benefit from being Assertions, but I'm not sure what data would be useful in the messages or what types to use, and don't know how to reproduce the Assertion so I wouldn't be able to test it beyond compiling.

**Comment by chief1983** [comment] 2017-02-19 00:24
Just an update, I haven't seen this assertion since, so nothing to report since we enhanced the assertion.

**Comment by chief1983** [comment] 2018-01-10 03:51
Still no sign of either of these being hit.  Not sure when FS2NetD will be back either, and by extension standalones.

**Comment by JohnAFernandez** [comment] 2020-09-09 03:23
Testers are not hitting this ever with the new multi builds. It's entirely possible this was from a misaligned object update packet (misalignment was often caused by model point shields).   I'm closing until we get another report of this assertion.

**Comment by JohnAFernandez** [comment] 2020-09-26 01:32
Of course, then I would be the one who hits it.  At least I can attach a debugger.  Let's see what happened.

**Comment by JohnAFernandez** [comment] 2020-09-27 20:44
It's starting to look like I had resolved a merge conflict incorrectly which caused this.

**Comment by chief1983** [comment] 2020-10-06 04:18
So you mean, the case in which you hit it, was probably not the same as whatever was originally causing this bug, and has already been fixed anyway?  In that case, we're good to close this again then, yes?

**Comment by JohnAFernandez** [comment] 2020-11-05 03:49
Yeah, I think so.  Let's risk it.

**Closed by JohnAFernandez** 2020-11-05 03:49 UTC
Labels: bug
