### ISSUE TITLE
Lua Error reporting the wrong line in the script

### ISSUE THREAD

**Issue by AxemP** [scp-fs2open/fs2open.github.com#1469] opened 2017-09-04 00:29 UTC
Given this script: https://pastebin.com/XMfbHxn7

And running the game, the game will report the error to be on Line 5 of the script. However line 5 of the script is an open brace. The game (or lua code) seems to think the lines start on the first valid lua line. If you remove all the lines so that `if true` is line 1, then the intentional error line appears on line 5.

This makes hunting errors for people who don't know this very hard.

**Comment by asarium** [comment] 2017-09-04 08:30
This is kind of expected since Lua reports the error line _inside_ the Lua source and not relative to the start of the table. I have an idea how this could possibly be fixed but at the moment this works more or less as designed.

**Comment by asarium** [comment] 2017-09-04 09:02
I made some changes that should fix the reported line number. At least the script you provided reports the correct line number now.

**Comment by chief1983** [comment] 2017-09-23 09:59
Is this confirmed fixed?

**Comment by asarium** [comment] 2017-09-24 08:38
It should be fixed by the PR I opened (see above) but that has not been merged yet.

**Closed** 2017-11-14 00:31 UTC
Labels: bug
