### ISSUE TITLE
Fade-ins misbehaving after mission restart?

### ISSUE THREAD

**Issue by MitoPL** [scp-fs2open/fs2open.github.com#2960] opened 2020-12-05 19:33 UTC
If you restart a cutscene mission that uses black fade-ins, they will become white fade-ins instead. This behaviour also seems to persist over subsequent runs.

My way of reproducing: launch Blue Planet Complete, launch the Icarus cutscene (via "continue campaign" option), when the mission ends, use "Restart mission" button. It seems to happen pretty consistently. Tested on 2020-10-01 nightly build, but I recall seeing this problem possibly as far back as a year ago, also in multiple cutscenes and missions.

**Comment by z64555** [comment] 2020-12-07 20:05
Confirmed, looking into it

**Comment by z64555** [comment] 2020-12-08 00:37
Ultimately the issue arose because of weird behavior using legacy functionality of the ```fade-in``` and ```fade-out``` sexps,   in addition to the Fade_out color not being initialized on mission start.

The ```fade-in``` sexp had a feature which would use the last color as set by ```fade-out``` However, ```fade-out``` did not save its color if it was black.  Thus, should any ```fade-out``` effect use any color other than the default black, the ```fade-in``` color reuse feature would malfunction.

The fade colors were only be initialized once on program start, so it would be possible for a color ```fade-out``` at the end of one mission and then be used for a ```fade-in``` effect on the next mission.  However this behavior was not explicitly documented anywhere, and in my opinion is bad design anyway.

**Comment by Goober5000** [comment] 2020-12-08 03:19
Fixed by #2967

**Closed by Goober5000** 2020-12-08 03:19 UTC
Labels: bug, sexps
