### ISSUE TITLE
Turret fov and orientation issues on retail aeolus model

### ISSUE THREAD

**Issue by Baezon** [scp-fs2open/fs2open.github.com#3299] opened 2021-03-15 18:50 UTC
Some retail models (I noticed it on the Aeolus) turret's seem to have incorrectly determined fov, causing them to only fire/track their targets if they are in the direction of their barrels. Additionally the Aeolus's rear top turret seems to have an inverted base orientation (points in the opposite direction, preventing the gun from being able to pitch down to shoot targets properly), and its gun submodels appear to always aim like 30 degress *below* their target, but I couldn't replicate those two on any other models, so I dunno if its specific to the Aeolus or what.

**Comment by Goober5000** [comment] 2021-03-28 02:10
I think the root cause is that `ship_get_global_turret_info` is calculating the wrong `gvec`.  This should be the turret normal, but instead it looks like it's returning the direction that the gun barrel is pointing.

**Comment by Goober5000** [comment] 2021-03-28 02:18
Or maybe it's the `turret_norm` itself that's bad.  This is strange...

**Comment by Baezon** [comment] 2021-03-28 02:24
That's the big weird part, which I really don't know how to consistently square: the turret normal isn't facing the same direction as the turret submodel's up vector. I'm not sure to what degree that's a fundamental problem or just something that's odd.

**Comment by Goober5000** [comment] 2021-04-18 21:42
I think this is actually not a bug.  To the extent that there were problems with the turret FOV, they were fixed in the other PRs.  @Baezon do you concur?

**Comment by Baezon** [comment] 2021-04-18 21:54
I would agree, for posterity: the gun angle and base angle issues existed for far longer than the recent changes, the gun angle problem being based on the model file itself. While its possible a solution or workaround could be found, it is not behavior affecting and specific to the aeolus and so not critical.

**Closed** 2021-04-18 22:34 UTC
Labels: not a bug
