### ISSUE TITLE
Async waiting not working correctly on their first invocation

### ISSUE THREAD

**Issue by Baezon** [scp-fs2open/fs2open.github.com#4432] opened 2022-06-22 04:50 UTC
I have seen many symptoms, waiting an incorrect amount of time, ~triggering multiple times~ (false positive on that one!), triggering not at all, and it's difficult to figure out exactly what's happening, but I have a straightforward test case at least.

```
#Conditional Hooks
$Application: FS2_Open

$On Mission Start: [
    mn.sendPlainMessage("message1!")
    async.run(function()
        async.await(mn.waitAsync(1.0))
        mn.sendPlainMessage("message2!")
    end)
]
#End
```
[test-sct.txt](https://github.com/scp-fs2open/fs2open.github.com/files/8954467/test-sct.txt)

This should send message1 immediately, and message2 after one second, but currently, will only send message1 and message2 is skipped (specifically everything in the function is run until the `waitAsync` afterward, nothing runs). If you restart, the issue seems to fix itself. If you quit and re-enter the issue returns. I tried switching to the newer timestamp system, didn't help.

**Comment by wookieejedi** [comment] 2022-06-24 16:10
Seems that the bug occurs with `$On Mission Start:` but not with 
```
$State: GS_STATE_GAME_PLAY

$On Gameplay Start: [
]
```

**Comment by Goober5000** [comment] 2022-06-25 02:19
If that's true, then it must have something to do with when the timing system is initialized.

**Comment by Goober5000** [comment] 2022-06-25 05:55
It actually has nothing to do with timestamps.  The following check is evaluating to true:
```
if (contextState == executor::IExecutionContext::State::Invalid) {
```
So the promise is aborted and the `timestamp_elapsed` check is never satisfied.

**Comment by Goober5000** [comment] 2022-06-25 06:04
And that, in turn, is caused by this:
```
IExecutionContext::State GameStateExecutionContext::determineContextState() const
{
	const auto depth = gameseq_get_state_idx(m_contextState);

	if (depth < 0) {
		// Our game state is not present anymore
		return IExecutionContext::State::Invalid;
	}
```
If I had to guess, I'd say that the context is being reset when the game crosses state boundaries (starting in `GS_STATE_START_GAME` and ending in `GS_STATE_GAME_PLAY`).  But I'll defer to @asarium to explain what is going on here.

**Comment by asarium** [comment] 2022-06-25 10:04
Yes, that is likely to be the issue. The game state execution context stuff is meant to deal with things like going to the options menu and handling cases where the mission is switched with a running coroutine.

With that specific hook, we capture the `GS_STATE_START_GAME` state for the coroutine and then once enough time has elapsed to continue it, we are in another state so the system "correctly" discards the coroutine.

The question now is whether this is unexpected behavior since `On Mission Start` is run even before any of the briefing is shown so at least in my opinion, changing the system so that coroutines that are started in this state do persist into gameplay would cause more confusion than the current system especially if we can simply use `On Gameplay Start` as @wookieejedi mentioned above.

In my opinion, this is expected behavior but that behavior is difficult to understand without knowledge about how the couroutine stuff works. An improvement here could be to add a better logging system to the executor system so that it plainly states somewhere why a coroutine is discarded.

**Comment by Baezon** [comment] 2022-06-26 07:01
That's understandable then, if unfortunate. I guess this more stemmed from not understanding the difference between Mission Start and Gameplay Start, and the fact that `mn.sendPlainMessage()` and others function just fine and actually happen at gameplay start caused me to believe that's when it was executed, confusing me why the initial print worked at the correct time, but a print that should happen later would not work. If message1 were not sent at all, it would point much more at the hook running not when I thought it would, and the fact that it _was_ sent 'correctly' threw me off that trail.

I still have concerns about async waiting running with strange timings, but the only definitive evidence here turned out to be largely unrelated, so I'm going to close this as resolved if there are no objections.

**Comment by Goober5000** [comment] 2022-06-26 23:01
Hold off on closing this.  I think it would make sense to add some simple `mprintf`s.

**Comment by Goober5000** [comment] 2022-06-28 17:56
Additional logging satisfies this, so closing.

**Closed by Goober5000** 2022-06-28 17:56 UTC
Labels: not a bug, scripting, documentation
