### ISSUE TITLE
Distance displayed in the targeting Brackets and the target monitor are not consistent

### ISSUE THREAD

**Issue by AdmiralNelsonFSO** [scp-fs2open/fs2open.github.com#4120] opened 2022-03-30 19:43 UTC
The targeting brackets and the target monitor do not display the same values for distance, as seen in this video: https://youtu.be/3Dah1mMwIEM

Testing shows me that the distance shown in the target monitor changes as I target different subsystems, whereas the distance displayed in the brackets does not change.  The HUD should be consistent; the targeting brackets should also display distance to subsystem, or both should display distance to bounding box or center.

**Comment by chief1983** [comment] 2022-03-30 19:47
Seems like knowing this allows you to get more information at one time than you could with both of those values being the same.  Perhaps this is by design?

**Comment by AdmiralNelsonFSO** [comment] 2022-03-30 19:50
But what distance do the targeting brackets actually display?  Is it the same as the distance SEXP? Without documentation, we can't tell the player which distance value to use or what the numbers shown mean.

**Comment by chief1983** [comment] 2022-03-30 19:54
Does the targeting brackets number change when you first target a subsystem?  If not I would assume it's displaying the overall object distance, I assume the center of the bounding box.

**Comment by AdmiralNelsonFSO** [comment] 2022-03-30 20:10
They don't AFAICS.  We should at least document which of the different distance SEXPs shows the same value as the targeting brackets.  For instance, in this mission the player is being told to maintain a certain distance from the target.  The correct distance SEXP that corresponds to the targeting brackets needs to be used so that the player can be told to look at the distance value in the brackets and have it be correct.

**Comment by EatThePath** [comment] 2022-03-30 22:03
Honestly, the status quo seems like neither a bug, confusing, or a problem. The difference seems quite intuitive. The corner target view in the corner doesn't change and frames the whole ship, so the distance it shows is the distance to what it shows, the ship. The camera's focus never changes, so the distance shouldn't change. The target brackets on the other hand don't frame the ship, they frame the current subsystem target. You want them to change because that distance is important, and having it on the brackets means it's right at hand when you need it most.

As a player I would assume directives or objectives are talking about distance to the ship unless they refer to a specific turret or subsystem. Otherwise I'd be able to change the mission flow by changing which subsystem I'm targeting. And as a player I need distance to subsystem for combat reasons and potentially need distance to ship if I ever have an objective about that. It's important in fact that the HUD not be consistent, because both pieces of information are important and there's probably missions out there needing both.

Where and how would the HUD behavior be documented better? All I can think of is the wiki, though where on the wiki I couldn't say. As for in FRED, the SEXP list having distance-to-center and distance-to-bbox next to distance-center-to-subsystem and distance-bbox-to-subsystem seems to pretty heavily imply that the first two are distance-to-ship, and the in-fred documentation for these also seems pretty clear to me. If you can point to where they are ambiguous then that would help in correcting it.

**Comment by EatThePath** [comment] 2022-03-30 22:05
I'll also note, it's possible to have the output of a distance-to sexp be displayed as a constantly updating number in an directive, so you can erase any ambiguity about where a directive is referencing and making the player constantly aware of the distance even when they're not targeting the thing by doing that.

**Comment by AdmiralNelsonFSO** [comment] 2022-03-30 23:16
Well, given that neither Goober or Chief, both of whom have over a decade of experience in the code, could answer the question,  I'd say it is clearly not well documented, though.  Honestly, I still don't have the answer to my question above - what distance SEXP corresponds to what the targeting brackets use? Is it -center or -bbox or just plain distance? That way I don't need to create a directive that potentially has a third number for distance.  
To improve the docs I'd just add to the SEXP description something like "This SEXP returns the same value as that used in the targeting monitor when a subsystem is selected" and "This SEXP corresponds to the distance shown in the targeting brackets."  There would then be no ambiguity.

**Comment by Goober5000** [comment] 2022-04-01 01:42
I dug into this a little more just now, and it's a bona fide bug.  Both distance indicators - targetbox and brackets - were using the function I thought they were using yesterday, but I discovered that when a subsystem is targeted, the distance for one gauge is recomputed using the center-to-center method, as opposed to the center-to-bbox method used everywhere else.

**Comment by wookieejedi** [comment] 2022-04-01 02:17
Good find! Would a possible fix involve a game settings flag?

**Comment by Goober5000** [comment] 2022-04-01 02:25
Still investigating.

**Comment by AdmiralNelsonFSO** [comment] 2022-04-01 10:57
Thank you for checking!

**Comment by Goober5000** [comment] 2022-05-07 18:57
@AdmiralNelsonFSO I believe this can be closed now that #4121 has been merged.  Do you concur?

**Comment by JohnAFernandez** [comment] 2023-01-05 16:21
Closing.

**Closed by JohnAFernandez** 2023-01-05 16:21 UTC
Labels: discussion, HUD, sexps, documentation
