### ISSUE TITLE
Should the game settings menu be enabled by default? (24.2)

### ISSUE THREAD

**Issue by MoerasGrizzly** [scp-fs2open/fs2open.github.com#6351] opened 2024-09-13 12:24 UTC
Even when launching FS2 retail (or indeed any mod), I get an in-game popup indicating that the In-Game Options menu is enabled but a save file could not be found.

Whilst I like the in-game options menu, should it be enabled by default on any mod that doesn't target FSO 24.2? The wiki still mentions that `$Enable in-game options:` is defaulting to No, and it's notable for any mod that doesn't have assets created.

**Comment by MjnMixael** [comment] 2024-09-13 13:30
The decision was that, yes, this should be enabled by default. There are a handful of changes that are correlated here. First, SCP is moving towards using In-Game Options for new toggle-ables, like Asteroth's new Mouse Control Settings added in #6136 , going forward instead of the command line. In order for those to be accessible, the menu must be enabled.

The popup you are seeing is related to in-game options because that also triggers a new options saving method that's per-mod rather than global to FSO. We made this decision because Solaris, FOTG, MediaVPs, BP, BtA are all so wildly different and often require fine-tuned settings for best performance. On first load of any mod, if the mod's own save does not exist then that popup shows up (should only show once) that you might need to reset some settings. It serves as both a notice that settings may not be what the player expects and a notice that many options are now available right in the game itself.

There will be some friction (hopefully very minimal) as mods update to 24.2 but that should subside as the player-base learns the new setup.

Relevant PRs to check out are #5895 , #5917 , #6045 , and maybe #6214 .

I know it's a lot, but I wanted to show our work that this has been an incremental and thoughtful process.

@wookieejedi was a big part of these discussions, too, and might have further insight.

**Comment by MjnMixael** [comment] 2024-09-13 13:33
Also wanted to add that the full text of the notice you got was "In-game Options are enabled but a save file could not be found. You may need to update your settings in the Options menu."

It was intended to not be taken as an error exactly but just a nudge to the options menu to double check it's all set up how the player wants. Should it be re-worded?

**Comment by MoerasGrizzly** [comment] 2024-09-15 18:23
I appreciate the detailed explanation :)

I think the message should be reworded, actually, because now it definitely reads like a pretty big warning.
To me, it reads like

1. A thing was done.
2. BUT [IMPORTANT] could not be found
3. You may need to change something!

to me that sets of all sorts of alarm bells. A SAVE FILE CAN NOT BE FOUND!? 

If I'd write a message like this I'd do it more in the line of:

1. There's something new!
2. This new thing can be changed!
3. Changing this is optional but cool!

Something along the lines of "There are new or updated options available for this mod. You may want to take a look at the options menu". Or "It seems like this is your first time running this mod since an update. Please check your options menu to see what's changed".
Or even, withhold the message until the player opens the options menu, and then hit them with the message:
"New options have been found! Default settings have been loaded, feel free to adjust them".

It doesn't have to be perfect, but
1. If FSO actually has trouble loading the mod settings, it'll show that pop-up every time anyway, so the player will know something is wrong.
2. In this particular case it's a lot better if the player viewing the message just ignores it (since it can be ignored, default settings are fine), rather then take unnecessary action (See also, this post).

**Closed** 2024-09-20 16:32 UTC
Labels: discussion
