### ISSUE TITLE
Dinky shockwaves aren't retail-compatible

### ISSUE THREAD

**Issue by MageKing17** [scp-fs2open/fs2open.github.com#774] opened 2016-08-08 20:09 UTC
Okay so I was looking into something completely different and I discovered that in 2005 (commit 78fab0c331836f883bc56d2d6b46f8e34f8cd0d5), wmcoolmon took a hardcoded division by 4 and turned it into a customizeable "dinky shockwave"/weapon arming system.

Or, at least, that's what he almost certainly _thought_ he was doing.

As it happens, I cannot find any way for the code responsible for the aforementioned division to have ever actually executed; even going back to the original Volition sources, `weapon_hit()` cannot, as far as I can tell, be called with a weapon for the other object. As a result, `SW_WEAPON_KILL` can never be set and the original division-by-4 that was the inspiration for the default stats of dinky shockwaves... never actually happened.

The new logic used by dinky shockwaves, however, doesn't check whether `weapon_hit()` got called with another weapon; it just checks `WF_DESTROYED_BY_WEAPON`. So now all weapons with shockwaves are, by default, exploding for 1/4th normal damage when shot down, and have been for the past 11 years.

To make matters worse, there was _another_ piece of unused code that was meant to multiply the damage back up by 4 when that shockwave hit a ship; presumably, it was expected to do the same thing under the new dinky shockwave system, except since it didn't do anything before, it still didn't do anything after. So if we fixed either end of this thing (either stop making weapons spawn dinky shockwaves without explicitly allowing for their presence, or make it so that dinky shockwaves still do full damage to ships), it would change the balance of any mission involving shooting down bombs balanced over the past 11 years, as suddenly shot-down bombs would deal 4 times as much damage as expected. Unfortunately, leaving it as-is means we're breaking retail balance.

I am honestly at a loss as to what should be done about this.

**Comment by Goober5000** [comment] 2016-10-16 23:21
Catching up on some of the old github notifications, so I just saw this now.

Our commitment to retail compatibility means that we need to fix this, but the question is how to do so.  The first approach is to just rip out dinky shockwaves altogether.  Is there any mod which uses them?

The second approach is to restore the original damage calculation while keeping the dinky shockwave overrides.  I'm assuming this is the approach that will be chosen, but then there is the problem of 11 years of history as you said.

A third approach is to adjust the calculation based on the "last modified" date in the mission.  I considered this when we ran into a similar issue on Scroll, but I ultimately decided that it was a case of trying to being too clever and might have unintended consequences.

Actually, the Scroll issue may shed light on this one.  When the HTL code was originally committed, it changed the briefing field-of-view for all missions, and missions created after a certain date had a different placement of icons as a consequence.  See the Mantis ticket:
http://scp.indiegames.us/mantis/view.php?id=3016

Fixing this restored the correct briefing FOVs for retail, but there were several years' worth of missions created that depended on the buggy FOV.  A feature was added to customize the briefing FOV on a per-mission basis if necessary.

Therefore, we should do the same thing with this issue.  Restore retail compatibility, but provide an FSO override to use the buggy behavior for mods that require it.  I think the dinky_shockwave code already allows you to specify damage calculations, so no additional flags should be necessary.

I am impressed that you managed to trace through the shockwave damage logic and pinpoint that issue.  Especially since that commit was from the era of large bundles of features per revision, and most of it had to do with the scripting system.

**Comment by wookieejedi** [comment] 2019-12-13 01:07
Since this is one of the reaming milestones, is the agreed solution the one Goober stated? `Restore retail compatibility, but provide an FSO override to use the buggy behavior for mods that require it. I think the dinky_shockwave code already allows you to specify damage calculations, so no additional flags should be necessary.`

**Comment by Goober5000** [comment] 2019-12-14 16:36
That is the strategy we have used in previous situations.  There are many examples: the briefing FOV issue mentioned above, several SEXPs, a couple ship/mission flags, and undoubtedly a few others that don't immediately come to mind.

I have not actually confirmed that the dinky_shockwave code allows you to specify damage calculations.  That is an assumption that should be double-checked.

**Comment by MageKing17** [comment] 2019-12-17 01:21
The dinky shockwave definition is the same as the regular, including ability to specify damage. The fix is as easy as removing the `wip->dinky_shockwave.damage /= 4.0f` on [weapons.cpp line 1135](https://github.com/scp-fs2open/fs2open.github.com/blob/bb2f19c1766e9470d9537419953e5e7b1a97a2ad/code/weapon/weapons.cpp#L1135), but it would probably be more helpful to add a mod table flag to toggle the behavior instead (so any mods suddenly going "oh god, shooting down bombs is suddenly way harder" can just flip a toggle instead of having to define damage for every shockwave).

**Closed** 2019-12-17 07:50 UTC
Labels: question, regression
