### ISSUE TITLE
HUD missing at 2160p or more with MVP2014

### ISSUE THREAD

**Issue by urielsd** [scp-fs2open/fs2open.github.com#998] opened 2016-10-01 23:59 UTC
The in-game HUD disappears when using resolutions above 1440p with MVP2014. If you use versions prior to 2014 the hud scales correctly and shows in screen even if it looks ugly for being so stretched. It's supposed to be related to the FSOpen game code and not the MVP2014.

FSOpen version 3.7.4; resolution used: 2160p (3840 x 2160)

**Comment by asarium** [comment] 2017-02-08 21:18
I can not reproduce this if I force FSO to run at 2160p. The HUD still shows up just fine.

**Comment by urielsd** [comment] 2017-02-08 22:48
@asarium Are you using MVP2014?

**Comment by asarium** [comment] 2017-02-08 22:50
Yes, I use them.

**Comment by MageKing17** [comment] 2017-02-08 23:14
It's possible a change since October fixed this bug, although I wouldn't have expected that...

**Comment by urielsd** [comment] 2017-02-26 15:10
I will run the fso installer, update wverything and report back.

**Comment by urielsd** [comment] 2017-02-26 18:10
Updated everything. Still having problems with -res 3840x2160 flag **and** MVPs 2014 turned on.
@asarium: which mod have you tested? I tested FSPort with fsportMVP2014

**Comment by asarium** [comment] 2017-02-26 18:40
I used the standard 2014 MVPs but the error may not appear in my case because I don't have a real 4K monitor, I just forced FSO to open a window at that size.

Does it still happen with the latest nightly? I tested it with a build from master and not 3.7.4 so there may have been a change which fixed this behavior.

**Comment by urielsd** [comment] 2017-02-26 18:43
Will try and report back. Thanks for the input asarium ;D

**Comment by asarium** [comment] 2017-02-26 18:45
Sure, no problem. Tracking down these issues is a bit hard since no SCP developer has a 4K screen so we  can't test this directly.

**Comment by urielsd** [comment] 2017-02-26 19:07
Tried nightly 32bit build from feb 26 2017. Problem persists.

_Used: fs2_open_3_7_5_20170226_9e50680_SSE2.exe_

**Comment by asarium** [comment] 2017-02-26 19:08
I'll try again on Windows. I think I can get my Video drivers to create a fake 4K display so maybe that will trigger the bug...

**Comment by urielsd** [comment] 2017-02-26 19:42
I wonder if the "Disable high DPI scaling" option has anything to do with this issue. I have to enable it since otherwise I cant choose anything with the mouse inside the game. 
Is there a way to load a mission rightaway when opening the exe without entering the flightdeck and briefing? If there is I can test this theory

**Comment by asarium** [comment] 2017-02-26 19:46
The High-DPI thing should not be needed anymore with the nightly builds but there is a way to jump directly into a mission by enabling the benchmark mode in the launcher (it's under Dev Tool) and then using the `-start_mission` parameter to launch a mission. E.g. with `-start_mission bp2_17`, you would launch the Icarus cutscene of BP complete but it works with all missions that exist in your selected mod. However, the mission may not have a briefing or else you will still need to press a button to get into the mission.

**Comment by urielsd** [comment] 2017-02-26 19:55
Tried nightly fs2_open_3_7_5_20170226_9e50680_SSE2.exe and i cant use select anything with the mouse if I do not use the "Disable high dpi scaling" option.
Do you know the name of the first mission in Silent Threat Reborn mod? I'll try to use the command line option you mentioned.

**Comment by asarium** [comment] 2017-02-26 19:57
I don't know the file name but you find that out by going into the Tech room and then the file name will be in the right column.

**Comment by urielsd** [comment] 2017-02-26 20:04
Tried it with fsport mvp 2014 , and you are right; I need to press commit and cant.

**Comment by urielsd** [comment] 2017-02-26 20:10
Here is a screenshot of the game running in window mode, 2160p, MVP2014, fsport, and no HUD in-mission mdu-08:
![nohud](https://cloud.githubusercontent.com/assets/16863660/23343195/5aa81698-fc46-11e6-85dd-b274ae9d8c36.JPG)

**Comment by asarium** [comment] 2017-02-27 09:35
Could you post a [debug log](http://www.hard-light.net/forums/index.php?topic=56279.msg1180359#msg1180359) when running the game like you did above? Maybe there is something in there that will help us.

I see that the display scaling is quite high in your screenshot so there may be an issue where FSO "thinks" it runs in a resolution that is too small since the OS reports a small window size. The debug log contains what resolution FSO runs in so that may give me an idea what is wrong and how I could reproduce it.

**Comment by The-E** [comment] 2017-02-27 09:41
Took a screenshot using simulated 4k via AMD's VSR
https://i.imgur.com/55Raxbf.png

The HUD scaling is obviously not ideal (as in, there really should be _some_), but it seems to me that the HUD is otherwise functioning as intended.

**Comment by asarium** [comment] 2017-02-27 09:43
Have you enabled display scaling? I suspect that it is somehow connected to that since FSO currently does not request a high-DPI window so that may interfere with how we determine the window size.

**Comment by The-E** [comment] 2017-02-27 09:48
Had to override it in the compatibility settings dialogue.

**Comment by asarium** [comment] 2017-02-27 16:59
#1269 should fix the DPI compatibility issues.

**Comment by urielsd** [comment] 2017-02-28 03:16
I use 400% dpi since otherwise the text in the screen looks way too small in my 50 inches 4K TV.
Have to use disable high dpi scaling since the mouse does not work properly without it.

**Comment by asarium** [comment] 2017-02-28 08:06
I used 300% scaling when I tried to reproduce the bug, I'll try again with 400%.

**Comment by asarium** [comment] 2017-02-28 14:19
Even with 400% scaling, the HUD still shows up for me. The manifest changes fixed the mouse interaction though so that's good, I guess...

**Comment by urielsd** [comment] 2017-02-28 20:31
Sorry people, my bad. Since I reinstalled the game the HUD shows no matter which DPI I use or resolution. The strange thing is that when I had the issue if I ran it at 1080p 100% dpi the HUD showed OK... Perhaps it was a flag I was setting but I highly doubt it since I tried several flags on/off even no flag at all. Anyway, it works fine. The HUD looks waaayy too small but at least it's there.

Sorry for the inconvenience guys, I swear I tested a lot of things before coming here.

**Comment by urielsd** [comment] 2017-02-28 20:32
The only thing that I changed besides reinstalling everything was the launcher; I'm using Launcher 5.5g since wxLauncher breaks at high DPI, but I don't think it has something to do with that because I tested running the command lines from cmd in Windows.

**Comment by asarium** [comment] 2017-02-28 20:47
I guess it was some kind of installation problem after all. At least the manifest changes should help compatibility for the future.

I'll close this issue. If you encounter it again, feel free to reopen it.

**Closed by asarium** 2017-02-28 20:47 UTC
Labels: bug
