### ISSUE TITLE
Directional lights may not be rendered under certain conditions

### ISSUE THREAD

**Issue by The-E** [scp-fs2open/fs2open.github.com#1598] opened 2018-02-10 08:40 UTC
This was found by FrikgFeek:

When a lot of point lights are present, directional lights (i.e. suns) are not getting rendered.
This can be demonstrated using this test mission: https://cdn.discordapp.com/attachments/223511391531827200/411726056169537557/Turn_off_the_sun.fs2
With this edited weapons.tbl: https://cdn.discordapp.com/attachments/223511391531827200/411726079024431114/weapons.tbl

Now, the code is actually supposed to make sure this doesn't happen: Directional lights are always supposed to be rendered.
The problem is in light_add_directional (lighting.cpp, line 201). When the background rendering code tries to add lights, the Lights array is already at capacity when lots of point lights are flying around.

**Comment by MageKing17** [comment] 2018-02-10 10:01
Could this be fixed by making directional lights used the deferred renderer?

**Comment by The-E** [comment] 2018-02-10 10:24
No, the issue is at a different level.
What's happening is that game_simulation_frame adds all point lights to the renderer (which in this test case rapidly exceeds the max number of 256 lights). Afterwards, during game_render_frame, backgrounds are evaluated. During that evaluation, light_add_directional is called but does an early exit because all light slots are already covered; The code that is supposed to make sure that directional lights (which runs later in the rendering process) thus never has a chance to do its job.

The fix, I think, is to remove the limitation on the number of _tracked_ lights. Let the rest of the code add as many lights as it wants; the max number of _rendered_ lights can be capped to 256, but we need to know what all lights are in the scene so that the light sorting code can do its job properly.

**Comment by asarium** [comment] 2018-02-10 11:02
I don't know if we can avoid doing a full screen pass for the directional lights. The current code works for the most part but a big problem is that directional lights change what is stored in the color buffer since that is used for applying the lighting effects. If a fragment is unlit by any directional light then it is black in the color buffer even though the texture of that object may have a different color.

I have noticed that point lights look "_weird_" (the surface is only lit with the light color but the actual surface color is not used) when they illuminate the dark side of an object and I am pretty sure that our hybrid lighting approach is the cause for this.

**Comment by The-E** [comment] 2018-02-10 11:07
That's a bit outside the scope of this bug, I think. How we treat directional lights in the end doesn't matter as much for the consistency of the overall look as making sure that directional lights reach the renderer in the first place, I think.

**Comment by asarium** [comment] 2018-02-10 11:12
Yes, sorry for going a bit off-topic.

On topic: I agree that it would be a good idea to convert the `Lights` array to a vector. `Static_light` uses pointers from the `Lights` array so that would need to be handled differently. It is probably sufficient to just use an index here instead of a pointer.

**Closed** 2018-02-12 10:40 UTC
Labels: bug
