### ISSUE TITLE
ASSERTION: "shield_pct >= 0.0f && shield_pct <= 1.0f" at ship.cpp:10326

### ISSUE THREAD

**Issue by MjnMixael** [scp-fs2open/fs2open.github.com#3374] opened 2021-04-11 04:23 UTC
Got this assert in BtA's **Bringing Down the Gavel** mission. I have narrowed it down to the change-ship-class sexp. Happens every single time.

Run BtA 1.5.8, play the that mission. Skip the cutscene and Alt-J to the asteroid site. There will be a couple seconds of dialog. When the convoy appears, use the specified keys (should be Alt-Shift-A, Alt-Shift-D, Alt-Shift-Z.. but you may need to check your Control Config for the custom keybinds to make sure they are set.) to take over Gavel's fighter. You'll swap into the Mustang class. Then just use Alt-Shift-D or Z to swap back to the Apollo. Assert.

**Comment by MjnMixael** [comment] 2021-04-11 05:15
Further information. This mission has had no major changes since as far back as 2017. Not to say that the mission isn't doing something stupid, but this whole ship-swapping thing it does used to work. If there's a mission issue, I'd appreciate help tracking it down as the assert is less than helpful.

I can say this does occur on 21.1.0. Testing much further back is quite difficult due to the complexity of the mod.

**Comment by JohnAFernandez** [comment] 2021-04-13 12:23
I reproduced it. It looks like the shield strength of the mustang at the assert is 400 but the max shield strength is 200. I haven't been able to do anything else with it yet, but I would double check that there's nothing setting the shield string too high in either sexps or in scripting.

**Comment by MjnMixael** [comment] 2021-04-13 14:12
Can you clarify which mustang has that issue? Is it Alpha 1 or Diamond 1?

**Comment by JohnAFernandez** [comment] 2021-04-14 00:39
Looks like Alpha 1

**Comment by MjnMixael** [comment] 2021-04-14 01:10
Hmm. Well Alpha switches from a Mustang (default shield HP 200) to a Loki (default shield HP 400). There's nothing else in the mission that explicitly sets shield energy as far as I can tell. No scripts are used for this hotswap.

I copied the hotswap on/off sexps to a blank mission and did not get the assert.. so that wasn't helpful. I removed all kinds of set-armor-type (shield), ship-copy-damage (I thought this was a good lead as it copies damage from a Loki to Alpha 1. But it happens after change-ship-class and removing it did not stop the assert), etc sexps to no effect. The only sexp that actually stops the assert if removed is the change-ship-class sexp.

**Comment by JohnAFernandez** [comment] 2021-04-14 01:27
hmmmmm.... Ok.  Let me look at things some more.  Maybe figure out why all the shield quadrants are getting set to 100 each before they are changed in change_ship_type

**Comment by JohnAFernandez** [comment] 2021-04-14 03:26
You have special shield hitpoints for Diamond 1 set to 400.  It gets transferred to Alpha 1, then when it tries to change back to a loki, it trips the assert.

**Comment by JohnAFernandez** [comment] 2021-04-14 03:41
Ok, I'm testing a fix. It looks like the ship-copy-damage sexp neglects to copy the special shield hitpoints from the source to the target, so FSO.

**Closed** 2021-04-15 01:07 UTC
Labels: bug
