### ISSUE TITLE
When send-messages overlap, the audio doesn't play

### ISSUE THREAD

**Issue by jlberman** [scp-fs2open/fs2open.github.com#6389] opened 2024-10-12 17:27 UTC
When multiple send-message SEXPs fire, and a message audio is currently playing, the message sent later won't play.

**Comment by MjnMixael** [comment] 2024-10-13 13:23
Likely an order-of-operations mistake I made when adjusting the code to stop playing message audio during this nightly run, assuming that's when the issue started? I'm exceptionally busy for the next few weeks and if SCP wants this fixed during this RC run then someone else may need to take a look as I just don't have the time.

**Comment by wookieejedi** [comment] 2024-10-13 18:14
> When multiple send-message SEXPs fire, and a message audio is currently playing, the message sent later won't play.

Just out of curiosity, do you have a set of events you could show a screenshot of and/or a test mission we could use as a reproducible test? Thanks!

**Comment by jlberman** [comment] 2024-10-14 01:37
![image](https://github.com/user-attachments/assets/021233c6-5fd0-4a13-b640-0194ece6a0d3)

**Comment by jlberman** [comment] 2024-10-14 01:37
GAGANAS 2 doesn't play

**Comment by jlberman** [comment] 2024-10-14 01:59
same thing here with interim3 and interim6. 
![image](https://github.com/user-attachments/assets/196ecaaa-b52d-4503-9f93-49a1c8001eb1)

**Comment by wookieejedi** [comment] 2024-10-14 02:18
Thanks!

**Comment by jlberman** [comment] 2024-10-14 03:04
@Goober5000 has access to the files in the Inferno SVN, FYI

**Comment by Goober5000** [comment] 2024-10-14 05:41
Finally had a chance to look at this.  Here's how the message looks in a text editor:
```
$Name: GAGANAS 2
$Team: -1
$MessageNew:  XSTR("Targets coming at us from multiple vectors. Orders, lead?", -1)
$end_multi_text
+Persona: Karim
+AVI Name: Head-TP3		;2
+Wave Name: M05_GAGANAS 2.ogg
```
It turns out that the last two lines end with CR, not CRLF like the others.  That, combined with the `;2`, causes the voice file to be omitted.  This is how the line is parsed by the mission parser:
```
+AVI Name: Head-TP3\t\t;2+Wave Name: M05_GAGANAS 2.ogg\n
```
The parser thinks everything starting from the semicolon is commented out.

So, this is a mission bug, not a code bug.  Fixing the line endings does the trick.

**Comment by Goober5000** [comment] 2024-10-14 18:40
Resolved in the mod itself.

**Closed by Goober5000** 2024-10-14 18:40 UTC
Labels: not a bug

**Comment by jlberman** [comment] 2024-10-14 18:43
Is there a way to revise the parser so that it catches these errors?  This thing was making me pull my hair out, because it wasn't showing up in the mission file itself.

**Comment by Goober5000** [comment] 2024-10-14 20:59
Yeah, that looks doable.  I'll open a new ticket for it.
