### ISSUE TITLE
Mission time runs slightly faster than clock time

### ISSUE THREAD

**Issue by Goober5000** [scp-fs2open/fs2open.github.com#3854] opened 2021-12-27 02:19 UTC
This can be seen in the happynewyear mod, where various events relating to the end-of-mission song (the "happynewyear" banner, the "twenty-nine" subtitle, and the actual end of the mission) occur sooner than they should.

According to my stopwatch, one in-game second is about .97 of a real second.

~~The discrepancy happened sometime between 19-RC2 and now, because on 19-RC2 all the events occurred at the expected times.~~  Maybe not, see latest comment.

**Comment by Goober5000** [comment] 2021-12-27 02:19
@notimaginative any ideas here?

**Comment by MjnMixael** [comment] 2021-12-27 02:28
Just wanting to make sure its known that the last time someone tried to synchronize these two, it affected all existing in-game cutscenes and other timed events in a negative way. I'm not opposed to a fix or if this is exactly the same as what occurred before, but I'd recommend caution.

**Comment by Goober5000** [comment] 2021-12-27 02:42
Noted.  Do you happen to remember the PR or issue for that last synchronization?

**Comment by MjnMixael** [comment] 2021-12-27 02:50
I've been searching for 20 minutes and I can't find it. I know for sure that it was committed to a public build and that it was eventually reverted. I spent a lot of time trying to convince whoever did it that it broke timed events (typically things timed to music). I want to say it was a zookeeper commit.. but I can't find anything on github or Mantis. I'm decently sure the issue predated Discord, so whatever IRC chats we had are long gone. I _think_ this all happened before BtA released, so it's been at least five years.

**Comment by Goober5000** [comment] 2021-12-27 03:06
After further investigation it looks like the environment has something to do with this.  I originally tested this mission on 19-RC2 on Windows 7, and all the timings were correct.  I just now tested this on 19-RC2 on Windows 11, and the timings are wrong.  So the problem must lie either in the system library or the code's interaction with it.

I did verify that the audio file's timing is correct.  The lyrics that occur at 0:44 and 3:20 in the song also occur at 0:44 and 3:20 in real time.

**Comment by notimaginative** [comment] 2021-12-27 03:54
I not sure that it's a bug, just the way it works. Mission time isn't supposed to be in sync with system time as far as I know. It is based on system time but it's definitely not "real time".

This may be the commit that MjnMixael is referring to: https://github.com/scp-fs2open/fs2open.github.com/commit/e98ff515358c8fdd1a0a621dc865bd01423744ef

And the linked HLP forum post discussing the issue: https://www.hard-light.net/forums/index.php?topic=79070.0

**Comment by notimaginative** [comment] 2021-12-27 04:10
And this appears to be the Mantis bug: http://scp.indiegames.us/mantis/view.php?id=2633

**Comment by MjnMixael** [comment] 2021-12-28 06:50
Yup, those appear to be what I remembered.

**Comment by Goober5000** [comment] 2021-12-31 20:18
I suspect this is due to the fact that timestamps and mission time use "dead reckoning".  Any rounding errors or changes in frame rate will accumulate over time because they are never synchronized to the total elapsed time.

I have an idea how to fix this but it will require some thought.

**Comment by Goober5000** [comment] 2022-01-03 07:00
After reading that thread, it's clear that this is the same issue as what was experienced back then, only manifesting in a different way.  A lot of the people on the thread were on the right track, but nobody fully understood the relevant design issues, or how fundamental they were.

The good news is that my new PR is a proper fix, and between taylor and myself, we should be able to nail down all the design considerations.  The bad news is that players may notice some slight timing changes, depending on how out-of-sync their game times were.

To say it in another way, the timing is going from subjective to objective measurement.  Previously, the timing being correct on one machine didn't guarantee that it would be correct on any other machine.  With this new PR, all machines will be consistent.

**Comment by naomimyselfandi** [comment] 2022-01-05 14:07
>  Previously, the timing being correct on one machine didn't guarantee that it would be correct on any other machine.
In the sense that mission events might fire at different times on different machines, or the sense that the discrepancy between mission time and clock time can be different?

**Comment by notimaginative** [comment] 2022-01-05 15:03
The issue is that, currently, mission time is weighted heavily by frame rate. So higher performing systems can progress differently from lower performing systems, with active mods and game options also having an impact. And as timestamps are based on the same calculation it means that there can be unknown timing variations between different players over the course of a mission.

**Comment by naomimyselfandi** [comment] 2022-01-05 15:40
I understand that. I'm just trying to get a sense of how much it matters in practice between machines (only in the sense that I haven't seen it brought up in this thread; I want to be clear that I'm not disagreeing with anyone, just asking if that's been analyzed).

**Comment by notimaginative** [comment] 2022-01-05 16:04
For something like audio streaming where the timer is different from the mission time it's going to be very noticeable when things are supposed to really line up but don't. An earlier comment here pointed out that the same build and mission on a Windows 7 machine works fine compared to a Windows 11 machine which is all wrong.

*When* the audio starts playing is based on the timestamp, so nothing should really be different there. But the actual audio streaming is based on the system clock so the longer the audio plays the more variation you are going to see between the audio and mission events.

I've personally never observed (or noticed, rather) more than a couple of seconds of variation over 10 or so minutes. And I'm not sure how many missions there are that are that dependent on the accuracy to function correctly. Until something actually breaks for them players may not even notice any difference.

**Comment by Goober5000** [comment] 2022-01-05 21:25
To give a concrete example, Joe recently played happynewyear on stream, and that has a subtitle which is cued to arrive at a specific point during a music track.  On Joe's machine, it was about 1/4 second early.  On my 8-year old Win7 laptop, it nails the time pretty accurately.  But on my brand new Win11 laptop, it is 3 seconds early.  All of these are using the same mission with the same build.

**Comment by naomimyselfandi** [comment] 2022-01-11 13:08
> On my 8-year old Win7 laptop, it nails the time pretty accurately. But on my brand new Win11 laptop, it is 3 seconds early. All of these are using the same mission with the same build.
Thank you for humoring me ([sincerity mode](https://tvtropes.org/pmwiki/pmwiki.php/Main/SincerityMode)). That's exactly the sort of analysis I was hoping for.

**Comment by Goober5000** [comment] 2022-01-11 17:17
Certainly.  The situation is subtle, yet has significant implications for mod development.  It's definitely a valid question.

**Closed** 2022-01-18 01:54 UTC
Labels: bug
