### ISSUE TITLE
Sound table parsing recently got more picky.

### ISSUE THREAD

**Issue by EatThePath** [scp-fs2open/fs2open.github.com#3292] opened 2021-03-14 03:26 UTC
21.1.0.20210313 crashes on some sound table entries that worked on 21.0, and appear to have worked(or failed silently I guess) for a very long time.

I encountered this with the blue planet sound table, on the line 

```
$Name:	327	maul.ogg 			0, 0.50, 1, 50, 400
```
The issue is that the file name does not have a comma before the next value. If corrected to 
```
$Name:	327	maul.ogg,			0, 0.50, 1, 50, 400
```
the crash goes away. The exact error is

```
sounds.tbl(line 350): Error: Expected int, found [ 0.50, 1, 50, 400].


Error: sounds.tbl(line 350):
Error: Expected int, found [ 0.50, 1, 50, 400].

File: parselo.cpp
Line: 312
```

This seems like a possible case of something that should have always worked the way it does now and thus notabug, but on the other hand it's a bit odd for this parsing to get more fragile and who knows how many mods out there have this landmine, so I figured I'd report it anyway and let yall decide what to do with it

I have not bisected and do not currently plan to. Crash should be reproducable by just launching current blue planet(1.1.4).

**Comment by Goober5000** [comment] 2021-03-14 03:31
This is not a bug.  The parsing didn't get more fragile, it got more strict.  The code will now properly catch parsing errors that it previously silently ignored.  In the past these errors could have resulted in a value of 0, a value that is off by a comma from the value expected, or some other unexpected result.

**Comment by naomimyselfandi** [comment] 2021-03-14 19:22
I think I can see both sides of this. On the one hand, silent failures are terrible from a bunch of different angles... but so's breaking backwards compatibility. My concern here is that someone opens up a mod - maybe a somewhat more obscure one that's not being actively maintained - and gets told, no, you don't get to play that, and rather than reporting it, just goes off to play something else.

I know the SCP goes out of their way to maintain backwards compatibility with _actual bugs_ when fixing them might screw up an existing mod. This change can make a mod _literally,_ not just practically, unplayable, so it seems philosophically inconsistent.

With that in mind, I'd really rather see this as a flag. Or is checking the `$Target Version:` in `game_settings.tbl` an option? That way, at least we know the new parsing behavior is only going to apply in a mod that's at least being maintained.

**Comment by Goober5000** [comment] 2021-03-14 19:38
There's a very simple and well-established way to handle this: select a prior FSO build.

We maintain backwards compatibility with FS retail; we don't promise to maintain compatibility with every single mod.  That would quickly balloon to an intractable problem.  Where would one stop?  Would we need to tie every git revision to a flag?

As MageKing said, the invalid table data never should have worked in the first place, and expecting it to continue to work is not realistic.  We don't even know what flavor of bugginess the parser interpreted the line as.  Was it 0, was it 5, was it a random value due to pointing at a bad area of memory?  To riff on Anna Karenina, bug-free mods all work correctly, but every buggy mod is buggy in its own way.

**Comment by naomimyselfandi** [comment] 2021-03-14 20:58
> There's a very simple and well-established way to handle this: select a prior FSO build. [...] I'd like to think that the community is industrious enough to eventually find the bug in the mod, report it, and fix it.

I guess I'm just apprehensive because there's nothing in the error that indicates it's related to versioning. We're both software developers, right? I think it's not nearly so obvious from the perspective of someone who just wants to shoot some space people. If there was something in the error message that encouraged people to check out HLP (or Discord (or both!)) and report it, I'd feel a lot better... although that's admittedly far from specific to this change!

Otoh, there's been some talk about automatically launching mods during CI to at least warn people about breaking changes. That'd also satisfy me. I dunno, maybe the real issue here is that FSO's error messages are aimed at developers and that's not necessarily appropriate in a released mod.



> [T]he invalid table data never should have worked in the first place, and expecting it to continue to work is not realistic. We don't even know what flavor of bugginess the parser interpreted the line as. Was it 0, was it 5, was it a random value due to pointing at a bad area of memory?

Hey, you're preaching to the choir here! I'm a huge believer in "fail early and fail loudly". I just think it's important to balance that with player experience - ultimately, FSO only exists because people keep playing it. Again, maybe there's a larger conversation about how FSO handles error reporting. (Maybe we should continue this on Discord?)

**Comment by Goober5000** [comment] 2021-03-17 02:47
> I guess I'm just apprehensive because there's nothing in the error that indicates it's related to versioning.

Sure, but that could apply to any error.

> We're both software developers, right?

Professionally?  I am; I didn't realize you were. :)

> If there was something in the error message that encouraged people to check out HLP (or Discord (or both!)) and report it, I'd feel a lot better... although that's admittedly far from specific to this change!

Yeah, I understand that this change might have tripped you up, but as you said this could apply to any change.

> Hey, you're preaching to the choir here! I'm a huge believer in "fail early and fail loudly". I just think it's important to balance that with player experience - ultimately, FSO only exists because people keep playing it. Again, maybe there's a larger conversation about how FSO handles error reporting. (Maybe we should continue this on Discord?)

I mean these are valid concerns, but they are also part and parcel of dealing with the FSO ecosystem - or any constantly changing project, really.  I would even say that FSO is better than most projects in the amount of attention it gives to modder concerns.

We can definitely continue this on Discord if you like.  I'll close this ticket.

**Closed by Goober5000** 2021-03-17 02:47 UTC
Labels: not a bug
