### ISSUE TITLE
'impossible' crash, laser_flag assert in aiturret.cpp:1222, possible memory management issue.

### ISSUE THREAD

**Issue by EatThePath** [scp-fs2open/fs2open.github.com#1791] opened 2018-07-11 19:19 UTC
[assert_fs2_open_log.txt](https://github.com/scp-fs2open/fs2open.github.com/files/2185889/assert_fs2_open_log.txt)
[assert_fs2_open_clipboard.txt](https://github.com/scp-fs2open/fs2open.github.com/files/2185890/assert_fs2_open_clipboard.txt)

I am experiencing an assert crash in very narrow circumstances. With a certain mod pack combination, on a certain mission, played a certain way, on debug builds, I get an assert error box with contents that show up in the fs2_open.log, and then two more error popups that don't appear in the log. I've attached both the log, and a paste of just the error messages.

In a discussion about this issue on Discord I've been informed that it should not be possible for this assert to be reached, and that thus nothing in the mod pack I'm using could logically be causing it. Having no lead whatsoever that makes sense, I'm just going to dump all the information I have on you about what is going on and hope something useful is contained within. I understand Axem encountered the issue before as well in different circumstances, but don't know any details there.

I'm working on a modpack that modifies Blue Planet. The mod adds weapons, ships, sounds, textures, and models, and also modifies many of the same from Blue Planet. The mission file in question is an exact copy of a blue planet mission file except that the player's default and available weapons/fighters, though the ships and effects in play in the mission are all modified themselves.

The mission is BP-04, "Journey of a Thousand Miles". At mission start there is a capital ship on team Unknown(purple) some distance away three alpha wing fighters, and there's also a jump node. The mission is otherwise empty. All three fighters are affected by turret-protect-ship "beam" and turret-protect-ship "laser". After some time the capship gets hit with change-iff "Hostile" and the player is tasked to shoot bits of it, and then shivans start showing up in the mission to fight everyone.

The moment when the ship switches to hostile is when the crash occurs. It only occurs if the player is close to the ship, if they keep their distance until after the switch nothing bad happens.

The crash only occurs with the addon mod active, I have not been able to make it happen in regular Blue Planet with the same play that reliably causes it in the addon. Problems also only manifest in debug builds, in non-debug no issues occur when I carry out the same test procedure.

I have observed this in 3.8.1.20180710_2dc2c06, 3.8.1.20180711_ccc727a, and Multilock-3.8.1-20180708. Probably a few earlier builds when I was intially tripping over it, but I didn't record those enough.

That's all I've got for now.

**Comment by TRBlount** [comment] 2018-09-13 22:53
I haven't been able to test this thus far, but reports from Spoon seem to corroborate that switching IFFs and having laser protect active on an object triggers this assert.

**Comment by Kingspoon** [comment] 2018-09-14 20:50
What I got when I ran into assert with a debug build:

`ASSERTION: "!((Objects[enemy_objnum].flags[Object::Object_Flags::Laser_protected]) && laser_flag)" at aiturret.cpp:1222
 
Assert: "!((Objects[enemy_objnum].flags[Object::Object_Flags::Laser_protected]) && laser_flag)"
File: aiturret.cpp
Line: 1222
 
ntdll.dll! NtWaitForSingleObject + 10 bytes
KERNELBASE.dll! WaitForSingleObjectEx + 156 bytes
fs2_open_3_8_1_x64_SSE2-DEBUG.exe! SCP_DumpStack + 367 bytes
fs2_open_3_8_1_x64_SSE2-DEBUG.exe! dump_stacktrace + 68 bytes
fs2_open_3_8_1_x64_SSE2-DEBUG.exe! os::dialogs::AssertMessage + 879 bytes
fs2_open_3_8_1_x64_SSE2-DEBUG.exe! find_turret_enemy + 2107 bytes
fs2_open_3_8_1_x64_SSE2-DEBUG.exe! ai_fire_from_turret + 3866 bytes
fs2_open_3_8_1_x64_SSE2-DEBUG.exe! process_subobjects + 729 bytes
fs2_open_3_8_1_x64_SSE2-DEBUG.exe! ai_frame + 2606 bytes
fs2_open_3_8_1_x64_SSE2-DEBUG.exe! ai_process + 435 bytes
fs2_open_3_8_1_x64_SSE2-DEBUG.exe! ship_process_post + 2319 bytes
fs2_open_3_8_1_x64_SSE2-DEBUG.exe! obj_move_all_post + 877 bytes
fs2_open_3_8_1_x64_SSE2-DEBUG.exe! obj_move_all + 932 bytes
fs2_open_3_8_1_x64_SSE2-DEBUG.exe! game_simulation_frame + 1467 bytes
fs2_open_3_8_1_x64_SSE2-DEBUG.exe! game_frame + 627 bytes
fs2_open_3_8_1_x64_SSE2-DEBUG.exe! game_do_frame + 183 bytes
fs2_open_3_8_1_x64_SSE2-DEBUG.exe! game_do_state + 343 bytes
fs2_open_3_8_1_x64_SSE2-DEBUG.exe! gameseq_process_events + 265 bytes
fs2_open_3_8_1_x64_SSE2-DEBUG.exe! game_main + 659 bytes
fs2_open_3_8_1_x64_SSE2-DEBUG.exe! actual_main + 162 bytes
fs2_open_3_8_1_x64_SSE2-DEBUG.exe! SDL_main + 47 bytes
fs2_open_3_8_1_x64_SSE2-DEBUG.exe! main_getcmdline + 320 bytes
fs2_open_3_8_1_x64_SSE2-DEBUG.exe! invoke_main + 45 bytes
fs2_open_3_8_1_x64_SSE2-DEBUG.exe! __scrt_common_main_seh + 295 bytes
fs2_open_3_8_1_x64_SSE2-DEBUG.exe! __scrt_common_main + 14 bytes
fs2_open_3_8_1_x64_SSE2-DEBUG.exe! WinMainCRTStartup + 9 bytes
[...]
[ This info is in the clipboard so you can paste it somewhere now ]
 
 
Use Debug to break into Debugger, Exit will close the application.
 
Int3(): From C:\Users\tyler_000\Documents\GitHub\fs2open.github.com\code\osapi\dialogs.cpp at line 355
ntdll.dll! NtWaitForSingleObject + 10 bytes
KERNELBASE.dll! WaitForSingleObjectEx + 156 bytes
fs2_open_3_8_1_x64_SSE2-DEBUG.exe! SCP_DumpStack + 367 bytes
fs2_open_3_8_1_x64_SSE2-DEBUG.exe! dump_stacktrace + 68 bytes
fs2_open_3_8_1_x64_SSE2-DEBUG.exe! debug_int3 + 82 bytes
fs2_open_3_8_1_x64_SSE2-DEBUG.exe! os::dialogs::Error + 821 bytes
fs2_open_3_8_1_x64_SSE2-DEBUG.exe! os::dialogs::AssertMessage + 1105 bytes
fs2_open_3_8_1_x64_SSE2-DEBUG.exe! find_turret_enemy + 2107 bytes
fs2_open_3_8_1_x64_SSE2-DEBUG.exe! ai_fire_from_turret + 3866 bytes
fs2_open_3_8_1_x64_SSE2-DEBUG.exe! process_subobjects + 729 bytes
fs2_open_3_8_1_x64_SSE2-DEBUG.exe! ai_frame + 2606 bytes
fs2_open_3_8_1_x64_SSE2-DEBUG.exe! ai_process + 435 bytes
fs2_open_3_8_1_x64_SSE2-DEBUG.exe! ship_process_post + 2319 bytes
fs2_open_3_8_1_x64_SSE2-DEBUG.exe! obj_move_all_post + 877 bytes
fs2_open_3_8_1_x64_SSE2-DEBUG.exe! obj_move_all + 932 bytes
fs2_open_3_8_1_x64_SSE2-DEBUG.exe! game_simulation_frame + 1467 bytes
fs2_open_3_8_1_x64_SSE2-DEBUG.exe! game_frame + 627 bytes
fs2_open_3_8_1_x64_SSE2-DEBUG.exe! game_do_frame + 183 bytes
fs2_open_3_8_1_x64_SSE2-DEBUG.exe! game_do_state + 343 bytes
fs2_open_3_8_1_x64_SSE2-DEBUG.exe! gameseq_process_events + 265 bytes
fs2_open_3_8_1_x64_SSE2-DEBUG.exe! game_main + 659 bytes
fs2_open_3_8_1_x64_SSE2-DEBUG.exe! actual_main + 162 bytes
fs2_open_3_8_1_x64_SSE2-DEBUG.exe! SDL_main + 47 bytes
fs2_open_3_8_1_x64_SSE2-DEBUG.exe! main_getcmdline + 320 bytes
fs2_open_3_8_1_x64_SSE2-DEBUG.exe! invoke_main + 45 bytes
fs2_open_3_8_1_x64_SSE2-DEBUG.exe! __scrt_common_main_seh + 295 bytes
fs2_open_3_8_1_x64_SSE2-DEBUG.exe! __scrt_common_main + 14 bytes
fs2_open_3_8_1_x64_SSE2-DEBUG.exe! WinMainCRTStartup + 9 bytes
kernel32.dll! BaseThreadInitThunk + 13 bytes
ntdll.dll! RtlUserThreadStart + 29 `bytes``

**Comment by FSCyborg** [comment] 2019-07-04 04:49
I've been reading the code for something like three hours, and I think I may have a theory. 

Spoon, did you use the "$Turrets prioritize ship target:" flag for the ship that changes IFF?

It looks like doing that can circumvent the portion of the code that protects ships (without circumventing anything else.

It branches off in line 1152.  Basically if "$Turrets prioritize ship targets" and there was a "previous" target, then it uses the first half of the code block and then ignores the rest where all the checks are.

The "previous" target is set in an entirely different function with no checks, `find_enemy()`, called by `ai_frame()` when it realizes that the iff changer does not have a target.  Once the ship changes iff status, `find_enemy()` suddenly starts working and sets one of the protected ships as the target.

Why does it not crash because if the ships are far away?  Because they are not within range and `get_nearest_turret_objnum()` (I am pretty sure) will not return a positive value unless there is a target in range.

I have not been able to test this.  I will give it a try tomorrow if I have time.

If anyone has time to look at this, please let me know if I missed anything or am going down the wrong track.  Just trying to learn.

**Comment by FSCyborg** [comment] 2019-07-04 05:07
Currently working on a possible fix for testing.

**Comment by Kingspoon** [comment] 2019-07-04 11:56
As far as I can remember, I don't think I've ever used the "$Turrets prioritize ship target:" flag 
I did work around the issue by placing the object out of turret range, which matches up with what you're saying about get_nearest_turret_objnum() etc.

**Comment by FSCyborg** [comment] 2019-07-13 13:38
Because Spoon's case is not yet fixed, I do not believe the bug is fixed by the pull request, but I believe it would get rid of closely related buggy behavior.

EatThePath let me know that he is going to try to reproduce the bug.  If he can, I will take another look.

**Comment by FSCyborg** [comment] 2019-07-19 02:02
Found it.  Has to do with "else if" vs. "if".  Once more than one of the protection flags was used at a time, this bug had a *chance* of raising its head, though I do not know what combination of things allows it to go through, since I cannot reproduce it.

**Closed** 2019-07-20 05:05 UTC
Labels: bug
