### ISSUE TITLE
Disable built in messages not working with modded files

### ISSUE THREAD

**Issue by AxemP** [scp-fs2open/fs2open.github.com#1344] opened 2017-04-26 23:32 UTC
I haven't been able to figure out exactly _which_ modded file is causing the issue, but it doesn't happen with retail data.

Test mission: https://pastebin.com/pnreGsNH
Play with JAD2.2

It has the global disable built in messages and disable built in command message options checked in the mission specs. But if you give fighters orders, they will give you those built in messages. But if I were to tick the disable built in messages for the ships through their ship editor screen, they will keep quiet.

I don't know what's causing it. I don't think its the modded messages.tbl because I copied and pasted it into my root /data/tables/ folder and the bug didn't manifest itself then. (But I could be wrong!)

**Comment by asarium** [comment] 2017-05-01 16:41
Did the option ever work? As far as I can tell, the value is never written to the mission file and isn't read when the mission is parsed. It can only be set by using SEXPs.

**Comment by AxemP** [comment] 2017-05-01 22:21
I am 99% sure this was working at some point before. I only began noticing it when things that shouldn't have been using personas suddenly did.

But why does it seem to work with retail data?

**Comment by asarium** [comment] 2017-05-02 08:12
There was an error in how the mission flags were saved to the mission file which should be fixed by #1345. Could you check if that changed anything? You'll need to compile a new version of FRED and then resave your mission with that build. You should check if the correct flags are set since that was affected by the bug.

**Comment by asarium** [comment] 2017-05-03 20:05
Well, I found why it works in retail but doesn't work in JAD2. Some script calls the `enable-builtin-messages` SEXP at mission start which overwrites the flag set in the mission specs editor.

The only script using that SEXP (as far as I can tell) is `vs2-sct.tbm`.

It looks like this is a mod problem and not an engine bug (but #1345 is still a good fix that should be merged).

**Comment by AxemP** [comment] 2017-05-03 23:27
_Huh..._

That makes a lot of sense now. I disable built in messages with the VN script because... who wants that to pop up randomly during a story sequence (since any in game messages also get routed to the script). But then obviously I want to re-enable after the end... I guess I'll just... deal with it manually...

**Comment by asarium** [comment] 2017-05-04 08:53
Ok, I'll close this issue since it's not a bug after all.

**Closed by asarium** 2017-05-04 08:53 UTC
