### ISSUE TITLE
Dumbfire secondary lead indicator not drawing past primary range

### ISSUE THREAD

**Issue by EatThePath** [scp-fs2open/fs2open.github.com#2335] opened 2020-04-15 16:40 UTC
From my testing it appears to be as the title says. If you have a non-homing secondary weapon with long range it's lead indicator won't be present unless the primary lead indicator is also visible. Tested on 20200409.

**Comment by Goober5000** [comment] 2020-04-28 00:03
Can you attach a test mission using retail assets?

I think I have a handle on this but I want to be sure.

**Comment by EatThePath** [comment] 2020-04-29 21:58
[LeadTest.zip](https://github.com/scp-fs2open/fs2open.github.com/files/4554863/LeadTest.zip)
This should be a viable playground for it. It's also a place to see behavior I feel is strange, which is that the lead indicator for homing secondaries is always drawn inside the primary lead indicator. Sort of understandable why that would be, but kind of strange to see it jumping around when switching between primaries.

The secondary indicator is drawn in the proper position for dumbfires though, so it's not really a problem, just something that's stuck out to me.

**Comment by Goober5000** [comment] 2020-05-03 19:08
> It's also a place to see behavior I feel is strange, which is that the lead indicator for homing secondaries is always drawn inside the primary lead indicator.

This is by design, since homing secondaries do not have an independent firing target.

The dumbfire lead indicator is now fixed though.

**Closed** 2020-05-04 20:12 UTC
Labels: bug
