### ISSUE TITLE
Disable orders not respected after engines are repaired after being destroyed

### ISSUE THREAD

**Issue by Baezon** [scp-fs2open/fs2open.github.com#2124] opened 2019-10-25 04:56 UTC
Disable orders seem to be simply ignored if the engines have been destroyed in the mission, regardless of their current status and if they're a valid target again. I haven't tested it, but I would suspect this holds for any subsystem.

**Comment by Goober5000** [comment] 2019-10-26 03:52
Confirmed.  In `ai_mission_goal_achievable`, the goals `AI_GOAL_DESTROY_SUBSYSTEM`, `AI_GOAL_DISABLE_SHIP`, and `AI_GOAL_DISARM_SHIP` all check the mission log.  Since the mission log already contains an entry, this goal is marked as already having been satisfied.

**Closed** 2019-11-08 21:06 UTC
