### ISSUE TITLE
Missing filename error for already-released missions

### ISSUE THREAD

**Issue by MageKing17** [scp-fs2open/fs2open.github.com#625] opened 2016-06-13 21:58 UTC
PR #549 has caused previously-working mission files to error on load. Quoth Lykurgos88, "There are now multiple missions in campaigns like Ryleh and Dimensional eclipse that work with 3.7.2 but not in 3.7.4 RC2 because of this same error." Obviously just reverting the PR is insufficient: the original problem it was meant to fix still needs addressed in some way, but breaking existing missions is a poor way to do it, especially since the command briefing code already checks whether or not the ANI filename is present.

A separate but somewhat-related question is why FREDers seem to be erasing the "`<default>`" ANI filename that FRED automatically populates the field with, but since FRED itself isn't responsible for the missing filenames, it doesn't really seem like something we can address in software (I mean, we could check for an empty string and save it as "`<default>`" instead, but that won't change the existing missions, so we still need to load them).

See also [this conversation on HLP](http://www.hard-light.net/forums/index.php?topic=91978.msg1820973#msg1820973).

**Comment by asarium** [comment] 2016-06-14 07:34
I am pretty sure that the assertion was caused by an empty file name in the fiction viewer section that was, for some reason, present in the mission causing the assert.

I could add a check for an empty filename after parsing it instead of relying on the paring code to do that.
The parser code could also just write the error to the debug log instead of showing an error. That would keep that diagnostic in place without breaking old mission.

**Comment by asarium** [comment] 2016-06-16 09:06
I'll submit a PR once I find the time to implement these changes.

Instead of using nprintf in missionparse.cpp wouldn't a proper warning be the better option? At that point an empty filename is never a valid file name so a warning shouldn't break existing missions.

**Comment by MageKing17** [comment] 2016-06-16 12:41
A Warning does make a certain amount of sense, and is a one-character change: just call `error_display(0, ...)` instead of `error_display(1, ...)`, and we even get to keep filename/line number information.

**Comment by asarium** [comment] 2016-06-16 17:19
That's not exactly what I meant, see #629 for my proposed solution.

**Comment by MageKing17** [comment] 2016-06-16 17:28
D'oh; sorry, I clearly wasn't fully awake when I read that last message. Looking over the PR now.

**Comment by asarium** [comment] 2016-06-18 17:31
Fixed by #629 and #630.

**Closed by asarium** 2016-06-18 17:31 UTC
Labels: regression
