### ISSUE TITLE
Thrusters not rendering right

### ISSUE THREAD

**Issue by AxemP** [scp-fs2open/fs2open.github.com#1806] opened 2018-07-21 21:44 UTC
This has been a problem for quite a while but no body's made an issue yet...

Engine thrusters tend to render through geometry.

![screen0027](https://user-images.githubusercontent.com/6625164/43040271-5524bffe-8d05-11e8-894f-334c5934fc89.png)
![screen0026](https://user-images.githubusercontent.com/6625164/43040272-57339cac-8d05-11e8-91c7-9be876120cd0.png)

Here's a mod with the new Rahu that really shows this easily: https://drive.google.com/open?id=1xAlWKUbOM-2OzdWlYFR5pgRrR_6Q-GZU

**Comment by MageKing17** [comment] 2018-07-21 22:02
Duplicate of #1238.

**Closed by MageKing17** 2018-07-21 22:02 UTC
