### ISSUE TITLE
Ship/weapon animation grid not working properly

### ISSUE THREAD

**Issue by Yarn366** [scp-fs2open/fs2open.github.com#347] opened 2015-09-16 00:41 UTC
Ever since deferred lighting was merged in with master, the grid effect used in the ship and weapon selection screens has not worked properly. The animation starts fine, but as soon as the grid starts to be revealed, the whole grid appears immediately instead of being revealed gradually.

The ship and weapon models themselves appear to be working fine. I also tested the FS1 effect and saw no problems.

**Comment by chief1983** [comment] 2016-03-16 20:47
I can reproduce this with retail data, on my Mac, comparing 3.7.2 to 3.7.4 RC1.  I will poke around and see if anyone can take a look.  @SamuelCho maybe?

**Comment by chief1983** [comment] 2016-03-16 22:08
To clarify, here is the basic steps I used to produce it:

Disabled mods
Enabled most of our graphical eye candy (GLSL, Post processing, shadows, etc)
Command line: /Applications/Freespace2/FS2_Open 3.7.4 RC1 (debug).app 3.7.4 RC1 -nomotiondebris
-missile_lighting -post_process -soft_particles -fxaa -fb_explosions -enable_shadows
-no_vsync -dualscanlines -targetinfo -rearm_timer -ballistic_gauge -ship_choice_3d
-weapon_choice_3d -3dwarp -snd_preload -no_set_gamma -brief_lighting -window
Used Ctrl+Shift+S in mission selection to choose 'Fog of War'
In ship selection, see that clicking ships in the available ships area exhibits the described bug - as soon as the 'reveal' line finishes expanding horizontally, the grid instantly appears, instead of appearing as the reveal line moves vertically down the page.  In 3.7.2, the correct behavior for the grid is seen when following these instructions (enable shadows has no effect is the only command line difference).

**Comment by chief1983** [comment] 2016-03-16 22:14
This command line batch also exhibits the problem: /Applications/Freespace2/FS2_Open 3.7.4 RC1 (debug).app 3.7.4 RC1 -nospec -noglow
-noenv -nomotiondebris -nonormal -noheight -nolightshafts -no_deferred -dualscanlines
-targetinfo -rearm_timer -ballistic_gauge -ship_choice_3d -weapon_choice_3d -3dwarp
-snd_preload -no_set_gamma -brief_lighting -window

As does: /Applications/Freespace2/FS2_Open 3.7.4 RC1 (debug).app 3.7.4 RC1 -nospec -noglow
-noenv -nomotiondebris -nonormal -noheight -nolightshafts -no_deferred -dualscanlines
-targetinfo -rearm_timer -ballistic_gauge -ship_choice_3d -weapon_choice_3d -3dwarp
-snd_preload -no_set_gamma -novbo -disable_fbo -disable_pbo -no_glsl
-disable_glsl_model -use_gldrawelements -no_batching -no_geo_effects -brief_lighting
-window

**Comment by asarium** [comment] 2016-03-16 23:05
@MageKing17 and I have been looking through the code a bit and found that the original code used a function that clipped all geometry, models and lines. The new code only clips the model. If that line clipping code is added then it still doesn't work because `gr_opengl_start_clip_plane` assumes that clipping is handled in the shader when running in GLSL mode but for lines there is no shader so the line never gets clipped.

**Comment by MageKing17** [comment] 2016-03-16 23:44
I've made a PR (#556) that sidesteps the issue of lines not using a shader, and the clipping plane being useless, by simply not drawing the grid below the scanline.

**Comment by asarium** [comment] 2016-03-17 14:50
Fixed in #557.

**Closed by asarium** 2016-03-17 14:50 UTC
Labels: bug
