### ISSUE TITLE
Axis Rotation Moveables Rotate Too Far

### ISSUE THREAD

**Issue by MjnMixael** [scp-fs2open/fs2open.github.com#4017] opened 2022-02-12 07:22 UTC
On the Jan 29 build I setup a movement system with Sexps to handle rotating an arm and a dish every 20 seconds. The sexp itself does a lot to make sure that the dish does not rotate through the arm or beyond 90 degrees from start. This all worked nicely on the Jan 29 build. Starting with the Feb 1 build, now the arms and dishes seem to rotate about twice as far to reach the specified rotation.

Here are videos to show what I mean. Note they are using time compression so you can see the issue easier.
Jan 29: https://youtu.be/BEr-3gtzUio
Feb 1: https://youtu.be/39Vi5fE9C00

The sexp that controls the movement is unchanged between the builds. It randomly chooses an arm (1-3) and rotates it to a random angle between -180 and 180. It then rotates the dish attached to that arm at a random angle, but checks the random value against the saved angle and does math to max the angle between 0 from start and +/-90 from start (the +/- is depending on which dish).

> $Formula: ( when 
>    ( true ) 
>    ( when-argument 
>       ( random-multiple-of "1" "2" "3" ) 
>       ( true ) 
>       ( string-concatenate-block 
>          "@endyArmResult[bta_endymion_arm1]" 
>          "bta_endymion_arm" 
>          "<argument>" 
>       )
>       ( string-concatenate-block 
>          "@endyDishResult[bta_endymion_dish1]" 
>          "bta_endymion_dish" 
>          "<argument>" 
>       )
>       ( modify-variable 
>          @armMovement[0] 
>          ( rand-multiple -180 180 ) 
>       )
>       ( modify-variable 
>          @dishMovement[0] 
>          ( rand-multiple -90 90 ) 
>       )
>       ( update-moveable-animation 
>          "GTI Endymion 1" 
>          "@endyArmResult[bta_endymion_arm1]" 
>          @armMovement[0] 
>       )
>       ( when 
>          ( string-equals "<argument>" "1" ) 
>          ( if-then-else 
>             ( < 
>                ( + @dish1Rot[0] @dishMovement[0] ) 
>                -90 
>             )
>             ( modify-variable 
>                @dishMovement[0] 
>                ( - -90 @dish1Rot[0] ) 
>             )
>             ( if-then-else 
>                ( > 
>                   ( + @dish1Rot[0] @dishMovement[0] ) 
>                   0 
>                )
>                ( modify-variable 
>                   @dishMovement[0] 
>                   ( - 0 @dish1Rot[0] ) 
>                )
>                ( do-nothing ) 
>             )
>          )
>          ( update-moveable-animation 
>             "GTI Endymion 1" 
>             "@endyDishResult[bta_endymion_dish1]" 
>             @dishMovement[0] 
>          )
>          ( modify-variable 
>             @dish1Rot[0] 
>             ( + @dish1Rot[0] @dishMovement[0] ) 
>          )
>       )
>       ( when 
>          ( string-equals "<argument>" "2" ) 
>          ( if-then-else 
>             ( < 
>                ( + @dish2Rot[0] @dishMovement[0] ) 
>                -90 
>             )
>             ( modify-variable 
>                @dishMovement[0] 
>                ( - -90 @dish2Rot[0] ) 
>             )
>             ( if-then-else 
>                ( > 
>                   ( + @dish2Rot[0] @dishMovement[0] ) 
>                   0 
>                )
>                ( modify-variable 
>                   @dishMovement[0] 
>                   ( - 0 @dish2Rot[0] ) 
>                )
>                ( do-nothing ) 
>             )
>          )
>          ( update-moveable-animation 
>             "GTI Endymion 1" 
>             "@endyDishResult[bta_endymion_dish1]" 
>             @dishMovement[0] 
>          )
>          ( modify-variable 
>             @dish2Rot[0] 
>             ( + @dish2Rot[0] @dishMovement[0] ) 
>          )
>       )
>       ( when 
>          ( string-equals "<argument>" "3" ) 
>          ( if-then-else 
>             ( < 
>                ( + @dish3Rot[0] @dishMovement[0] ) 
>                -90 
>             )
>             ( modify-variable 
>                @dishMovement[0] 
>                ( - -90 @dish3Rot[0] ) 
>             )
>             ( if-then-else 
>                ( > 
>                   ( + @dish3Rot[0] @dishMovement[0] ) 
>                   0 
>                )
>                ( modify-variable 
>                   @dishMovement[0] 
>                   ( - 0 @dish3Rot[0] ) 
>                )
>                ( do-nothing ) 
>             )
>          )
>          ( update-moveable-animation 
>             "GTI Endymion 1" 
>             "@endyDishResult[bta_endymion_dish1]" 
>             @dishMovement[0] 
>          )
>          ( modify-variable 
>             @dish3Rot[0] 
>             ( + @dish3Rot[0] @dishMovement[0] ) 
>          )
>       )
>    )
> )
> +Name: Control Arm Movement
> +Repeat Count: -1
> +Trigger Count: -1
> +Interval: 20

**Comment by BMagnu** [comment] 2022-02-12 07:55
This was caused by #3995.
Fixed in PR #4019.

Though to note: #3995 _was_ expected to change the behaviour of the axis moveable (just that it did so buggily).
Pre-#3995, the axis moveable was relative, i.e. calling the update function with 90 would increase the angle by 90. This was not intentional, and is now fixed / changed to portray absolute angles, i.e. calling the update function with 90 will always result in the same angle being reached. This is to enable the moveable to be updated while it is still moving without losing precise position information.

**Comment by MjnMixael** [comment] 2022-02-12 14:42
Are you saying I won't need most of the fancy sexp then? Sounds like I can just throw a random value at it between 0 and -90 each time and it'll work as I expect.

**Comment by BMagnu** [comment] 2022-02-12 14:52
That is the intention, yes.
Moveables, in their concept, should always be told where to end up, no matter what the last state of the moveable was, including it not having completed their movement.
That this wasn't the case for axis moveables was simply a bug so far.

**Closed** 2022-02-13 01:30 UTC
