### ISSUE TITLE
Briefing Icons have unintuitive behavior for FREDers

### ISSUE THREAD

**Issue by MjnMixael** [scp-fs2open/fs2open.github.com#3860] opened 2021-12-28 01:36 UTC
Briefing icons can be set to an icon image; this is the retail class. It ranges from Fighter to Juggernaut and includes things like Asteroid, Jump Node, Waypoint, Unknown, Planet, etc. Briefing icons also have a model field where you can select the ship class to be shown. FSO has a feature where you can designate custom icons per ship class in the ships.tbl. If a model has an icon specified in the ships.tbl then that icon will be used instead of the selected icon image from the above field.

However, if you select a model with an icon, then the Icon Image field gets greyed out because it's unused... sort of... If the Icon Image is set to Asteroid or a handful of others while at the same time a model is chosen that has its own icon specified, then the model's icon will be used but the model displayed when the player clicks on it will be the asteroid. It's like Asteroid, Jump Node, et al are overrides to the model but not the icon while at the same time the image field is greyed out so you can't change it anymore. The FREDer has to select a model that doesn't have an icon specified, then change the Icon Image away from any of the overrides, then change the model back to the ship class they want to use.

Personally, I think the easiest solution is simply to not grey out the Icon Image field in FRED. 

I don't have a ready-made mod to show this practice off, but you could pretty easily do it with the currently released BtA mod. It makes extensive use of per-ship-class icons.

**Comment by jg18** [comment] 2021-12-28 21:33
Looked into this. Although not graying out the "Icon Image field" would be easy (technical details: remove `&& (sip_bii_ship < 0)` in briefingeditordlg.cpp:621), I'm concerned about potential unintended consequences, especiallly given how little I knokw about this code.

Perhaps there's a way to enable that field in the cases where it's currently grayed out unnecessarily? It looks like that bit of code currently doesn't differentiate between "selected object doesn't have a custom briefing icon" and "slected object isn't a ship", or maybe the control's "enabled" status isn't always getting updated (via call to `update_data()`) when it shold be.

Would like to get @goober5000's take here.

**Comment by Goober5000** [comment] 2022-04-28 03:02
Finally had a chance to look at this.  The convention the game engine uses is that if Asteroid, Jump node, etc., are selected, the pop-up window will display a specific model.  So with that in mind, the *ship class* should be grayed out if one of those cases is selected.

The reason that the per-ship-class icon causes the icon type to be grayed out is that the icon type will always be overridden.  But if the icon type pre-empts the ship model, you end up with a case of duelling priorities.

**Comment by MjnMixael** [comment] 2022-04-29 03:42
Unsubbing. While this is undoubtedly something that needs fixing, I don't have energy to deal with Goober's insane design philosophy and can't contribute further here.

**Comment by MjnMixael** [comment] 2022-05-19 02:14
Whatever what changed is decidedly worse. Now I cannot create icons using any icon type that are also unlickable in FSO. Can we just not grey out any fields ever and not try and FRED for the FREDer? That would be the ideal way to fix this. I don't want FRED trying to tell me what I can and can't do.

**Comment by MjnMixael** [comment] 2022-05-19 02:27
Furthermore if I open missions that previously used an icon type in combination with a custom ship icon to create unclickable ship icons and open the briefing, FRED removes those ship icons and changes all of these icons to whatever icon type was selected, usually Planet.

**Comment by naomimyselfandi** [comment] 2022-05-19 11:46
For an example of BTA using the Planet type to make an icon unclickable, look at "The Will to Act" from _Slaves of Chaos_ (`bta1_m1_05` if you need to use `skipmemymissionyo` for it). We have a "ship" called Special Briefing Icons. The icon for Lt. Sermakh's face uses that class, but it doesn't make sense to click on it since there's no associated model, so it has the Planet type. Before now, this resulted in a big Vasudan face that you couldn't click on.

The ability to assign the Planet type and still get the custom icon is not the problem. We _use_ that functionality. The problem is only that it's tedious to assign. You have to create a briefing icon, then change it to a class that doesn't have a custom icon (pretty much everything in our modpack that actually appears in missions has a custom icon), then change the type, then change it to the icon you actually want. Letting the FREDer change the icon type, even if the class has a custom icon, would get around that problem.

**Comment by Goober5000** [comment] 2022-05-20 01:15
Ok, I'll take a look.

**Comment by Goober5000** [comment] 2022-05-20 02:47
It's been a few years, but as I recall, the reason for disabling the icon type selection was to make it clear that changing the icon type would have no effect.  Obviously there is *one* effect that was missed at the time - the fact that clicking on a Planet type would not display the pop-up.

Are there any features other than the "clickable-ness" that are enabled by changing the icon type?  Or, put another way, if things stayed as they are but a "non-clickable" flag was added, would this satisfy the project needs?

I'm definitely in favor of using clever hacks to do cool stuff, but I'm also in favor of following the "make invalid state unrepresentable" principle when possible.  For most situations, having an icon type that conflicts with a custom ship class is an invalid state.

**Comment by naomimyselfandi** [comment] 2022-05-20 12:25
So, there are a couple things here.

First, I have to question whether changing the icon type really creates an "invalid state". If Alice goes into the briefing editor, makes an icon from a cruiser, and changes it to a fighter (with a custom icon), then leaving the icon as Cruiser is _irrelevant,_ not invalid. Secondly, FRED second-guessing the user and mucking up the icons is a huge problem. We've come to rely on that functionality and, to be frank, I can't say with any confidence which missions do and don't use it. I'm not looking forward to manually checking every briefing in our upcoming release to make sure they didn't get saved with a too-new version of FRED. It will also cause problems for us when we make bug fixes post-release. This "feature" actively causes issues for the people who originally opened this issue.

As for introducing an "unclickable" flag... sure, I guess. There's also the special treatment of Unknown and Unknown Wing (and, for completeness' sake, Jump Node, although that could probably be omitted). It does seem to introduce unnecessary risk compared to just not greying out the dropdown. If you really want to go that route, please make sure that the way we use Planet is still respected - call it a legacy configuration setting if that makes you feel better ([not sarcastic](https://tvtropes.org/pmwiki/pmwiki.php/Main/SincerityMode)).

**Comment by Goober5000** [comment] 2022-05-20 13:54
Ok, you make good points.  I'll hold off on the "unclickable" flag, and I'll remove the code that disables the dropdowns and resets the ship classes.

**Comment by Goober5000** [comment] 2022-05-23 02:37
Closing now that #4289 has been merged.

**Closed by Goober5000** 2022-05-23 02:37 UTC
Labels: bug, fred
