### ISSUE TITLE
Crash when loading mission with fiction text and jump node twice

### ISSUE THREAD

**Issue by Yarn366** [scp-fs2open/fs2open.github.com#412] opened 2015-11-04 05:31 UTC
There seems to be something wonky going on between the fiction viewer and jump nodes, but only with debug builds. Performing the following steps crashes the game:

1. Start a debug build. (The crash doesn't occur with release builds.)
2. Load a mission that has both fiction text and a jump node.
3. *Without continuing past the fiction viewer*, quit the mission.
4. (Optional) Load any number of missions that have fiction text but no jump nodes, and quit them *from the fiction viewer*.
5. Repeat step 2 using the same mission or a different one.

This crash occurs as far back as 3.6.16 and the first post-3.6.14 Windows nightly (r9285) but not in 3.6.14. Unfortunately, Visual Studio 2015 does not seem to compile revisions that old, so I can't figure out myself when exactly this bug was introduced.

Here's the error message that this crash produces:

Assert: (check == this || !check)
File: jumpnode.cpp
Line: 230

ntdll.dll! ZwWaitForSingleObject + 21 bytes
kernel32.dll! WaitForSingleObjectEx + 67 bytes
kernel32.dll! WaitForSingleObject + 18 bytes
fs2_open_3_7_3_AVX_20151103_0ea25e7-DEBUG.exe! SCP_DumpStack + 354 bytes
fs2_open_3_7_3_AVX_20151103_0ea25e7-DEBUG.exe! WinAssert + 194 bytes
fs2_open_3_7_3_AVX_20151103_0ea25e7-DEBUG.exe! CJumpNode::SetName + 125 bytes
fs2_open_3_7_3_AVX_20151103_0ea25e7-DEBUG.exe! parse_waypoints_and_jumpnodes + 267 bytes
fs2_open_3_7_3_AVX_20151103_0ea25e7-DEBUG.exe! parse_mission + 617 bytes
fs2_open_3_7_3_AVX_20151103_0ea25e7-DEBUG.exe! parse_main + 482 bytes
fs2_open_3_7_3_AVX_20151103_0ea25e7-DEBUG.exe! mission_load + 228 bytes
fs2_open_3_7_3_AVX_20151103_0ea25e7-DEBUG.exe! game_start_mission + 192 bytes
fs2_open_3_7_3_AVX_20151103_0ea25e7-DEBUG.exe! game_enter_state + 520 bytes
fs2_open_3_7_3_AVX_20151103_0ea25e7-DEBUG.exe! gameseq_set_state + 303 bytes
fs2_open_3_7_3_AVX_20151103_0ea25e7-DEBUG.exe! game_process_event + 242 bytes
fs2_open_3_7_3_AVX_20151103_0ea25e7-DEBUG.exe! gameseq_process_events + 149 bytes
fs2_open_3_7_3_AVX_20151103_0ea25e7-DEBUG.exe! game_main + 787 bytes
fs2_open_3_7_3_AVX_20151103_0ea25e7-DEBUG.exe! WinMain + 328 bytes
fs2_open_3_7_3_AVX_20151103_0ea25e7-DEBUG.exe! __tmainCRTStartup + 296 bytes
fs2_open_3_7_3_AVX_20151103_0ea25e7-DEBUG.exe! WinMainCRTStartup + 13 bytes
kernel32.dll! BaseThreadInitThunk + 18 bytes
ntdll.dll! RtlInitializeExceptionChain + 99 bytes
ntdll.dll! RtlInitializeExceptionChain + 54 bytes

**Comment by Goober5000** [comment] 2015-11-04 05:41
What that assert means is that the code found another jump node with the same name as the one it's trying to create.

The root cause of all this is most likely that exiting the fiction viewer does not properly clean up the mission data, leaving some things (such as jump nodes) still in memory.

**Comment by Goober5000** [comment] 2015-11-04 05:58
PR #414 prevents the crash.

**Comment by niffiwan** [comment] 2015-11-08 04:35
#414 is merged so we can close this

**Closed by niffiwan** 2015-11-08 04:35 UTC
