### ISSUE TITLE
BP2s ammo packs do not work with nightlies.

### ISSUE THREAD

**Issue by MoerasGrizzly** [scp-fs2open/fs2open.github.com#4952] opened 2022-11-29 21:42 UTC
Ammo packs in BP2 do not work in current nightly releases.
They do work in FSO 22.2

To test:
Launch Her Finest Hour
fire a couple of grimmlers
use ammo pack

note difference in results.

**Comment by MjnMixael** [comment] 2022-11-29 21:46
Betting ammo packs were scripted and this is a duplicate of #4830

**Comment by MjnMixael** [comment] 2022-11-29 21:58
[bp2-equip-sct.zip](https://github.com/scp-fs2open/fs2open.github.com/files/10117669/bp2-equip-sct.zip)
yup

**Comment by MoerasGrizzly** [comment] 2022-11-29 22:53
Oh dear...

well at least BP2 is publically available so this _should_ be a little bit easier to test.

**Closed** 2022-12-13 18:51 UTC
Labels: bug, duplicate

**Comment by MoerasGrizzly** [comment] 2022-12-14 23:15
@BMagnu Bug has not fully been fixed, a new issue has arisen instead: When firing your primary weapons in Her Finest Hour (for instance), all ammo is instantly replenished as if an ammo pack were used. However, the ammo pack is not selected by default at the start of the mission, and the ammo pack itself is not used up.

Weirdly enough, cycling through your primary weapon selections even once prevents the issue from occuring. But as long as you don't touch the period key at all, you get infinite ammo on both your sidhe and grimmlers.
