### ISSUE TITLE
Crash from unknown radar range

### ISSUE THREAD

**Issue by Svedalrain** [scp-fs2open/fs2open.github.com#3136] opened 2021-01-12 21:41 UTC
I crashed when saving hud color settings during a mission. I got an error about "unknown radar range of -1" in radarsetup.cpp line 479. I haven't reproduced yet.

When I restarted FSO (in debug mode), I got a warning about the unknown radar range of -1, and got a warning that radar range was set to default. Brain is dumb and I don't recall if I crashed or not. Debug log [here](https://fsnebula.org/log/5ffe14729ec55980ffa8d59b).

Attaching a minidump from the initial crash and pilot files from before the start in debug: [radarrangecrash.zip](https://github.com/scp-fs2open/fs2open.github.com/files/5804960/radarrangecrash.zip).

**Comment by Svedalrain** [comment] 2021-01-12 21:44
I am still crashing on application start, just after the warning setting the unknown radar range to default, when the pilot select screen would appear.

**Comment by z64555** [comment] 2021-01-13 02:20
The member in question is `hudconfig.cpp::HUD_config::rp_dist`.

There are 4 places where it may be set:
1. `hudconfig.cpp::hud_set_default_hud_config(player *)`
2. csg read
3. plr read
4. Rolling from keycontrol.cpp

In none of those places is it ever set to -1.
In 1, it sets `rp_dist` to the "default" of `RR_INFINITY`.
In 2 and 3, there is a bounds check.  It gives you a warning and sets `rp_dist` to `RR_INFINITY`.
In 4, The rolling is positive, and once it hits the maximum it is reset to 0 (which is RR_SHORT)

So, as stated on discord this appears to be an action at a distance, something is messing with its singleton struct, HUD_config, in such a way that its nuking everything.

Where did you change the color settings? Is it a retail menu, like the one in the F2 options?

**Comment by JohnAFernandez** [comment] 2021-01-13 02:38
The function `hud_config_backup()` creates a "copy" of the `HUD_config` struct.  So it may be setting the HUD_config fields from the backup and getting bad data from there.

**Comment by Svedalrain** [comment] 2021-01-13 02:43
Changed it in the retail hud color menu. I think I saved settings--I set all the gauges to full white and my player file seems reflect to that--and I used the escape key to exit out of the menu.

I continued to experience the crash after the opening cutscene, each time getting a "setting unknown radar range to default" warnings, so the radar range might just be the most visible/first thing that trips a warning/error...which @JohnAFernandez's hypothesis would explain

**Comment by JohnAFernandez** [comment] 2021-01-13 21:34
This is not fully fixed.

**Comment by JohnAFernandez** [comment] 2021-01-14 02:26
This bug is *so* rare though.  I tried to reproduce about 100 times with different combinations of situations and it crashed *once*. We are shooting in the dark with this one.  I am going to move it to 21.2 because we will be able to try the undo system by then.

**Comment by JohnAFernandez** [comment] 2021-02-10 05:13
While testing, this luckily reproduced while I was on a debug build.  Turned out to be a negative array index write! Copy of the struct was completely fine.

**Comment by JohnAFernandez** [comment] 2021-02-10 13:52
Hopefully fixed now.  Please reopen if you encounter this after the 2/10 nightly.

**Closed** 2021-02-10 19:52 UTC
Labels: bug
