### ISSUE TITLE
Shadows not being casted in certain conditions.

### ISSUE THREAD

**Issue by FrikgFeek** [scp-fs2open/fs2open.github.com#1595] opened 2018-02-06 20:19 UTC
I get no shadows in missions with 2 suns where the suns are close to eachother. I've attached some test cases. Shdtst-1 has 2 nearby suns, Shdtst-2 has them far apart, and Shdtst-3 has them at the same position(0, 0, 0). In cases 1 and 3 no shadows are cast on any of the ships in the mission.

[Shdtst-1.fs2.txt](https://github.com/scp-fs2open/fs2open.github.com/files/1700660/Shdtst-1.fs2.txt)
[Shdtst-2.fs2.txt](https://github.com/scp-fs2open/fs2open.github.com/files/1700661/Shdtst-2.fs2.txt)
[Shdtst-3.fs2.txt](https://github.com/scp-fs2open/fs2open.github.com/files/1700662/Shdtst-3.fs2.txt)

.txt because github doesn't support .fs2 files so just remove the .txt extension.

**Comment by asarium** [comment] 2018-02-07 12:00
I can reproduce this issue but I don't know what is causing it yet. I confirmed that the shadow maps are rendered correctly in both cases so rendering those is not the problem.

The shadow view matrix looks a bit odd in the first test mission but I don't know if that is the cause of the issue yet.

**Comment by asarium** [comment] 2018-02-10 16:08
The cause for this is simply that all but the first sun are not affected by shadows (since shadow maps are only rendered for the first sun). This means that the properly shadowed lighting of the first sun gets "overwritten" by the other suns which don't have any shadowing since they have a much larger intensity.
The second test does not show this issue since the second sun is placed at such an angle to the major shadow receiving surfaces that it doesn't apply much lighting to those surfaces.

In my opinion this cannot be fixed without serious changes to how FSO renders shadows. If you want shadows to be visible in your mission then you shouldn't use secondary suns.

**Comment by Goober5000** [comment] 2018-06-08 19:58
Closing since this issue seems to be unsolvable and there has been no follow-up in several months.

**Closed by Goober5000** 2018-06-08 19:58 UTC
Labels: bug
