### ISSUE TITLE
FRED has become nagari sensitive and is being manipulated into changing sexps.

### ISSUE THREAD

**Issue by MoerasGrizzly** [scp-fs2open/fs2open.github.com#5099] opened 2023-01-10 17:31 UTC
[bp2-23.zip](https://github.com/scp-fs2open/fs2open.github.com/files/10385186/bp2-23.zip)

War In Heaven's Universal Truth's opening scene has a section where Sathani bombard earth. With my more recent updates to BP, this stopped working. I never could figure out why that was.

This is the relevant SEXP tree. This represents the tree in its working order: 
![afbeelding](https://user-images.githubusercontent.com/9599230/211619457-558fa00e-8fbe-4789-a784-6e08a4711a74.png)

However, when the mission is saved, this happens: 
![afbeelding](https://user-images.githubusercontent.com/9599230/211620513-b80c886d-3f9e-4cab-a174-3f64fc6ab3ec.png)

Behaviour also occurs in FSO 22.2 stable. Behaviour occurs without warning, regardless if a fast debug build is used or not. 

Notably, when the mission is loaded into FSO without FRED's alterations, it works correctly. It no longer does after it is loaded and saved in fred, even if that is the only action taken.

**Comment by MoerasGrizzly** [comment] 2023-01-10 17:32
Pieces of my mission are floating away. HELP! HEEEELP!

**Comment by Goober5000** [comment] 2023-01-10 17:45
I see that `<argument>` has been changed to `0`.  Is that the only difference?

**Comment by MoerasGrizzly** [comment] 2023-01-10 17:49
> 

I have no idea.

**Comment by The-E** [comment] 2023-01-10 18:28
This is reproducible in a minimal example. 
![image](https://user-images.githubusercontent.com/280879/211632268-a9eaa6ff-6141-4e27-b492-a1eebcae5ec7.png)
After closing the event editor and saving, this becomes:
![image](https://user-images.githubusercontent.com/280879/211632383-450fabb4-ef36-42cf-9d00-1f1ee9e42a68.png)

After editing the mission manually and reloading it, the event shows up correctly - but the next save operation nukes the `<argument>` again.

**Comment by MoerasGrizzly** [comment] 2023-01-10 18:49
regression occurs somewhere between FSO 19 and FSO 21

**Comment by The-E** [comment] 2023-01-10 18:51
After researching, the issue is connected to the fix for #2314.
In this particular constellation, the check at sexp.cpp:4787 fails because `<argument>` is neither an empty string nor does it pass the "can_construe_as_integer" check, which makes FRED insert a `0` instead.

**Closed** 2023-01-10 20:33 UTC
Labels: bug, regression, fred
