### ISSUE TITLE
Using "get-object-x"/y/z on a string variable does not return correct coordiantes

### ISSUE THREAD

**Issue by jpd-0rph3u5** [scp-fs2open/fs2open.github.com#2101] opened 2019-10-09 07:06 UTC
I was trying to apply [this](https://github.com/scp-fs2open/fs2open.github.com/pull/2063) to a wing that arrives in waves in order to make the waves always appear to the same side of a target ship - with the option of switching out the target ship via variable.

As it presents itself however, using get-object-x/y/z on a string variable does not return the correct coordinates.

Clean Test Mission:
https://1drv.ms/u/s!AqsFAmZ9eyuXonmJynMktt_6ZBoP?e=9l8ZO6

**Comment by Goober5000** [comment] 2019-10-11 19:54
This is not suitable as a test mission.  I'm not familiar with what is supposed to happen, and there are way too many events.  Furthermore, it is not "clean"; it is based on the MediaVPs.

Make a new mission with as few events as possible that demonstrates the bug.  Ideally, this should be only one event, executing one time.  (Or at least only one event that contains get-object.)

It was completely impractical to run the mission through a debugger due to the number of times get-object was called, particularly with get-object.

**Comment by Goober5000** [comment] 2019-10-11 19:55
Sorry for the accidental closing; GitHub spazzed out on my for some reason.

**Comment by Goober5000** [comment] 2019-11-13 04:07
It's been a month.  Do you have a clean, simple, mission that reproduces the problem?

**Comment by FSCyborg** [comment] 2019-12-12 04:16
I created a simple test mission.  I cannot reproduce.  It seems to behave like normal for me.
[test string variables.fs2.txt](https://github.com/scp-fs2open/fs2open.github.com/files/3953778/test.string.variables.fs2.txt)

**Comment by Goober5000** [comment] 2019-12-12 06:39
I figured as much.  I haven't experienced any problems myself.  Closing the issue.

**Closed by Goober5000** 2019-12-12 06:39 UTC
