### ISSUE TITLE
Cannot launch nightlies since 30 July on Ubuntu

### ISSUE THREAD

**Issue by naomimyselfandi** [scp-fs2open/fs2open.github.com#5571] opened 2023-08-23 15:13 UTC
Launching a nightly since 30 July through Knossos fails without producing a debug log. I've seen the same behavior with retail, stock MVPs, and BTA.
> Starting /home/naomi/games/FreespaceOpen/bin/FSO-23.1.0-20230816/linux/fs2_open_23_1_0_20230816_4812ff529_x64-FASTDBG.AppImage failed! (return code: 1)

OS information:
```
naomi@Melchior:~$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.5 LTS
Release:	20.04
Codename:	focal
```

**Comment by naomimyselfandi** [comment] 2023-08-25 13:50
Edited to clarify that I tested with retail as well.

**Comment by notimaginative** [comment] 2023-08-28 03:39
The builds are made with a compiler version that's too new to run on anything but the latest distro releases. Hopefully we can get that sorted out in short order.

**Comment by naomimyselfandi** [comment] 2023-08-29 22:02
I'm pretty new to the Linux world, but I think I'm running the latest release now, and I still have the same problem:
```
naomi@Melchior:~$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 22.04.3 LTS
Release:	22.04
Codename:	jammy
```

**Comment by naomimyselfandi** [comment] 2023-08-29 23:34
Confirming that updating Ubuntu did, in fact, resolve this issue. Sorry, I'm pretty new to the Linux world ^^

**Comment by notimaginative** [comment] 2023-08-30 21:35
No worries. I believe we've identified the problem and have a couple of possible fixes in mind. So hopefully this will get resolved soon enough.

Thanks for the bug report, and confirming that an OS update did indeed fix it for you. 👍

**Comment by Goober5000** [comment] 2023-09-16 19:43
Looks like this was auto-closed via #5606.  It might be fixed, but we don't know for sure yet.

**Comment by notimaginative** [comment] 2023-09-17 23:39
There is a temporary fix for this issue now in place. FSO builds, starting with the Sep 17 nightly, should be working on older Linux versions once again.

The problem is that a g++ update we don't want is getting integrated into the newer build images. So for a proper long-term fix we'll have to sort that issue out so we aren't stuck using an old build image forever. That's something we'll tackle soon, but for now at least everything should be back to normal.

**Comment by TRBlount** [comment] 2023-09-18 00:11
Should we leave this open for now then?

**Comment by notimaginative** [comment] 2023-09-18 00:15
Probably, as the current fix is more of a workaround. I'll try and sort out a better solution this week.

**Comment by notimaginative** [comment] 2023-09-22 19:31
Finally tracked this down to the use of the `ubuntu-toolchain-r` ppa in the docker build image which includes a new `libstdc++` as required by newer compilers. Older versions are not available without limiting us to g++-8 and clang-10.

Statically linking the lib is probably the best solution, to avoid managing symvers. Works for me on a plain 20.04 vm so we'll see how it goes in the wild.

**Closed** 2023-09-23 02:13 UTC
