### ISSUE TITLE
Support ship steals primary weapon's ammo since 26 October build

### ISSUE THREAD

**Issue by tomimaki** [scp-fs2open/fs2open.github.com#2140] opened 2019-11-11 15:46 UTC
If support ship docks and primary weapon ammo loadout is less than max, then ammo counter decreases. Counter doesn't stop until you shake off thug. :p
Secondary weapons are not affected.

**Comment by FSCyborg** [comment] 2019-11-11 15:47
Oh oh.  What did I do?  I'll take a quick look today.

**Comment by FSCyborg** [comment] 2019-11-11 16:38
@tomimaki, does it steal them one at a time?

**Comment by tomimaki** [comment] 2019-11-11 16:39
Yes.

**Comment by FSCyborg** [comment] 2019-11-11 16:41
Which mod or tables are you using?  I think it has to do with how I set up the parsing.

**Comment by tomimaki** [comment] 2019-11-11 16:43
Blue Planet

**Comment by FSCyborg** [comment] 2019-11-11 17:42
I reproduced and then made a tiny change and it seems to be working now.  The issue is that the table was setting flags after ammo increment, but the ammo increment depended on the flags to tell whether it was a ballistic primary or not. #2141

**Comment by Goober5000** [comment] 2019-11-11 20:53
Fixed via #2141

**Closed by Goober5000** 2019-11-11 20:53 UTC
